### ISSUE TITLE
Add task title and description to all task types

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#110]
Currently you can only assign task names and tasks to the type `flow.View`. I would be cool if you could always assign a title and description to create better overviews including i18n support.

**Comment by kmmbvnr** [comment]
Yep, that's good point. Currently it could be achived by adding  [TaskDescriptionMixin](https://github.com/viewflow/viewflow/blob/master/viewflow/flow/base.py#L347) to custom node subclass
