### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'myprocess'.

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#111]
`AttributeError: 'Process' object has no attribute 'myprocess'.`
[This](https://github.com/viewflow/viewflow/blob/master/viewflow/models.py#L115) does not work if you use multi table inheritance.
As the package itself makes use of MTI if should be supported I guess.

**Comment by kmmbvnr** [comment]
Mm, could you show what is model inheritances sample that don't works?

**Comment by codingjoe** [comment]
It's very simple:
```
class MyIntermediateProcess(Process):
    pass

class MyProcess(MyIntermediateProcess):
    pass

class MyFlow(Flow):
    process_cls = MyProcess
```

**Comment by kmmbvnr** [comment]
I can't reproduce https://github.com/viewflow/viewflow/blob/master/tests/test_models.py#L27
