### ISSUE TITLE
setup.py requires Django to be already installed when doing a source install.

### ISSUE THREAD

**Issue by amusikal** [viewflow/viewflow#117]
When using zc.buildout/mr.developer to install source from repository, an exception is raised at setup.py line 10 as it tries to import django.core.management to call `compilemessages` . At this stage of the process Django is *not* available on the $PATH.

**Comment by kmmbvnr** [comment]
yep, that's a problem

you can use pypi version right now

**Comment by amusikal** [comment]
Many thanks, Mikhail!

**Comment by kmmbvnr** [comment]
Fixed in 7d68804
