### ISSUE TITLE
Save incomplete tasks

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#121]
I have a quick question. Is there a good way to save incomplete tasks?
I only saw "save" and "save & continue"

**Comment by kmmbvnr** [comment]
That's actually open question. In django we have no standard class-based view for save and continue.

**Comment by codingjoe** [comment]
[`generic.UpdateView`](https://docs.djangoproject.com/en/1.8/ref/class-based-views/generic-editing/#updateview)?

**Comment by codingjoe** [comment]
@kmmbvnr I already implemented that for us:
```
class SavableViewMixin:
    @Activation.status.transition(source=STATUS.PREPARED, target=STATUS.ASSIGNED)
    def save_task(self):
        self.task.save()

    def activation_done(self, *args, **kwargs):
        if '_save' in self.request.POST:
            self.save_task()
        else:
            self.done()

    def message_complete(self):
        if '_save' not in self.request.POST:
            super(SavableViewMixin, self).message_complete()

    def get_success_url(self):
        if '_save' in self.request.POST:
            return self.request.get_full_path()
        return super(SavableViewMixin, self).get_success_url()
```
If you're interested I can make a PR.

**Comment by kmmbvnr** [comment]
I've added cookbook reference  sample to show how the tasks could be set on pause and get out of user's inbox - https://github.com/viewflow/cookbook/tree/master/viewflow_pause

**Comment by codingjoe** [comment]
@kmmbvnr oh, cool thanks!
