### ISSUE TITLE
examples with tox fail - ERROR: InvocationError: could not find executable 'migrate'

### ISSUE THREAD

**Issue by edwardotis** [viewflow/viewflow#122]
Steps to reproduce:

Cloned master branch
mkvirtualenv --python /usr/bin/python3 viewflowexamples
Modified tox.ini for python3.4 and just django 1.8 (see below)
Then ran following commands:

myself@my-vm:~/dev/viewflow$ workon viewflowexamples
(viewflowexamples)myself@my-vm:~/dev/viewflow$ pip install -U tox
Requirement already up-to-date: tox in /home/myself/Envs/viewflowexamples/lib/python3.4/site-packages
Requirement already up-to-date: virtualenv>=1.11.2 in /home/myself/Envs/viewflowexamples/lib/python3.4/s
ite-packages (from tox)
Requirement already up-to-date: pluggy<0.4.0,>=0.3.0 in /home/myself/Envs/viewflowexamples/lib/python3.4
/site-packages (from tox)
Requirement already up-to-date: py>=1.4.17 in /home/myself/Envs/viewflowexamples/lib/python3.4/site-pack
ages (from tox)
(viewflowexamples)myself@my-vm:~/dev/viewflow$ python --version
Python 3.4.3
(viewflowexamples)myself@my-vm:~/dev/viewflow$ tox migrate
py34_dj18 installed: amqp==1.4.7,anyjson==0.3.3,beautifulsoup4==4.4.1,billiard==3.3.0.21,celery==3.1.18,cove
rage==3.7.1,decorator==4.0.4,dj-database-url==0.3.0,Django==1.8.4,django-easy-pjax==1.2.0,django-extra-views
==0.7.1,django-filter==0.11.0,django-fsm==2.2.1,django-jenkins==0.18.1,django-material==0.4.1,django-templat
e-debug==0.3.5,django-webtest==1.7.8,flake8==2.5.0,ipdb==0.8.1,ipython==4.0.0,ipython-genutils==0.1.0,kombu=
=3.0.26,mccabe==0.3.1,path.py==8.1.2,pep8==1.5.7,pexpect==4.0.1,pickleshare==0.5,psycopg2==2.6.1,ptyprocess=
=0.5,pyflakes==1.0.0,pytz==2015.7,simplegeneric==0.8.1,singledispatch==3.4.0.3,six==1.10.0,traitlets==4.0.0,
uWSGI==2.0.11.2,waitress==0.8.10,WebOb==1.5.1,WebTest==2.0.18,wheel==0.24.0
py34_dj18 runtests: PYTHONHASHSEED='2667059167'
py34_dj18 runtests: commands[0] | migrate
ERROR: InvocationError: could not find executable 'migrate'
_________________________________________________ summary __________________________________________________
ERROR:   py34_dj18: commands failed

------------------
tox.ini
------------
[tox]
;envlist = py34_dj18, py34_dj16
envlist = py34_dj18
skipsdist = True

[testenv]
setenv=PYTHONPATH={toxinidir}
commands = {posargs:python ./manage.py test tests}
passenv = DATABASE_URL
deps =
       singledispatch==3.4.0.3
       django-fsm==2.2.1

       django-filter==0.11.0
       django-webtest==1.7.8
       webtest==2.0.18
       git+https://github.com/viewflow/django-material.git

       # helloworld example
       celery==3.1.18
       kombu==3.0.26

       # shipment example
       django-extra-views==0.7.1

       # tests dependencies
       dj-database-url
       django-jenkins
       flake8
       coverage<3.999
       psycopg2

       # deploy and development
       django-template-debug
       ipdb
       uwsgi

[testenv:py34_dj18]
basepython=python3.4
deps = {[testenv]deps}
       django==1.8.4

;[testenv:py34_dj16]
;basepython=python3.4
;deps = {[testenv]deps}
;       django==1.6.11 # rq.filter: 1.6,<1.6.999
;       https://bitbucket.org/andrewgodwin/south/get/e2c9102ee033.zip#egg=South

[testenv:travis]
basepython=python3.4
commands = coverage run --branch --source=viewflow manage.py test viewflow tests
           pip uninstall South -y
           pip install django>=1.8.4 -U
           coverage run --append --branch --source=viewflow manage.py test viewflow tests
           coveralls
usedevelop = True
deps = {[testenv]deps}
       django==1.6.11
       South
       coveralls

**Comment by kmmbvnr** [comment]
tox usage:

```
# run all tests under all envs
$ tox

# run tests under specific env
TOXENV=py34-dj18 tox

# run specific test
TOXENV=py34-dj18 tox python manage,py test tests.test_flow_signal.Test.test_signal_usecase

# run examples
TOXENV=py34-dj18 tox python manage,py migrate --settings=examples.settings
TOXENV=py34-dj18 tox python manage,py loaddata <path_to_json> --settings=examples.settings
TOXENV=py34-dj18 tox python manage,py runserver --settings=examples.settings
```
