### ISSUE TITLE
Job task schedule in future

### ISSUE THREAD

**Issue by martinhill** [viewflow/viewflow#123]
Hi,

I would like to be able to schedule a celery Job task to execute at a future time, like this:

```python
    send_job = celery.Job(tasks.send_message) \
        .Eta(lambda p: p.send_time) \
        .Next(this.end)
```

Canceling scheduled job should revoke the task from workers.

Current implementation does not support this, but is it on the roadmap? I would be willing to try to implement myself in a PR.

Thanks
Martin

**Comment by kmmbvnr** [comment]
Yes. This is actual desired behaviour for celery job tasks. That's wat I always missed from ad-hock celery tasks usage in generic django project.

.Eta() is a nice idea, since this is core celery functionality.

PR would be really appreciated. Thank you.

**Comment by codingjoe** [comment]
:+1:

**Comment by martinhill** [comment]
Ok, I shall try to start coding this week, and aim to finish before end of month/year.

**Comment by somghosh** [comment]
Hello @kmmbvnr  I came across a little improvement here, that could be useful. Celery Jobs have a status = STATUS.SCHEDULED and Process.get_task() does not pick this up correctly because it excludes this status by default

    def get_task(self, flow_task, status=None):
        """
        Return task instance
        """
        if status is None:
            status = [STATUS.NEW, STATUS.ASSIGNED, STATUS.STARTED]
        elif not isinstance(status, (list, tuple)):
            status = [status]

        return self.flow_cls.task_cls._default_manager.get(
            process=self, flow_task=flow_task, status__in=status)


I am happy to put in a pull request if you agree. Many thanks

**Comment by kmmbvnr** [comment]
That's only default value for `status`. If you need a schedulled job, you can call `.get_task(flow_task, status=STATUS.SCHEDULED`)
