### ISSUE TITLE
Issue with Hello world example

### ISSUE THREAD

**Issue by brspradeep** [viewflow/viewflow#125]
I am trying to use the viewflow package with Python 3.4.3 and django 1.8.4.
I am trying to play with hello world example. However it seems that it seems celery package (due to sharedtask). If I install using pip the django-celery package, it seems to work fine but for one issue. After approval, it gives an error
OSError at /helloworld/3/approve/10/

[Errno 111] Connection refused
I tried to dig deep into the stack and I found out that celery is using amqp eventhough kombu and django:// are specified in settings.py.

As I am new to Viewflow, Celery and Kombu, any help is welcome( I am not too good at python and django for that matter :-))

Regards,
Pradeep

**Comment by kmmbvnr** [comment]
Use 

`tox python manage.py runserver --settings=examples.settings` command to run examples
