### ISSUE TITLE
Celery and Viewflow compatibility on Django 1.9 

### ISSUE THREAD

**Issue by cesclondon87** [viewflow/viewflow#129]
I follow this https://github.com/celery/celery/tree/3.1/examples/django for celery setup but viewflow doesn't work.
When I launch celery with: "celery -A myproj worker -l info" return this error:

``
  File "/Users/fcaspani/PycharmProjects/no-cookiecutter/serionet/venv/lib/python3.4/site-packages/viewflow/managers.py", line 92, in _clone
    return super(ProcessQuerySet, self)._clone(klass, setup, **kwargs)
TypeError: _clone() takes 1 positional argument but 3 were given
``

If I uninstall viewflow, celery works properly.
Thanks for the support

Francesco

**Comment by kmmbvnr** [comment]
pypi version of viewflow have no support for django 1.9

Use django 1.8 or viewflow/master brach

**Comment by cesclondon87** [comment]
Thanks!
