### ISSUE TITLE
Python 3.5 on CI tests

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#134]
Refs #133

As I said earlier in my mail, this is absolutely vital to us.
We can't have a big part of our production code note run on our tech stack.

I'm happy to make the changes, if you tell me how you want it.

**Comment by kmmbvnr** [comment]
I don't actually understand why python 3.4 vs python 3.5 is so crucial.

I'm using travis to get nice badges on repo only. For this I need to run tests under django 1.6/1.8/1.9 at the same time combine coverage (--append) and put them to coveralls. I don't want to increase package maintenance cost by supporting travis build and solving travis-only errors. Like this one with celery tests happens only on travis container with python 3.5 and not repeated on any other machines.

So i think, if you need some CI setup you can setup an intranet jenkins instance.

**Comment by kmmbvnr** [comment]
So, now you can have a jenkins instance with a custom settings and run the tests like

```
cat > jenkins_settings.py << EOF
from tests.settings import *
INSTALLED_APPS += ('django_jenkins',)
EOF

DJANGO_SETTINGS_MODULE=jenkins_settings REDIS_CACHE_URL=redis://127.0.0.1:6379/1 DATABASE_URL=postgres://postgres:postgres@localhost/viewflow TOXENV=py35-dj19 tox python manage.py jenkins
```

**Comment by kmmbvnr** [comment]
Mm, I found the way not to increase the maintenance cost for me, but still use travis and tox without duplication or ability to simulate travis build locally.

1. Drop [testenv:travis] from tox.ini
2. Preserve (python - 3.4) in the .travis.yml to start builds on the old travis container
3. Add before_install step to get python3.5 on the old container (https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure)
4. Add following commands in .travis.yml to run the build

```
tox -- coverage run --branch --source=viewflow manage.py test tests
coveralls
```

This would collect the coverage from all django's at the same report to get nice coverage badge, and reuse all env's from tox.ini for the tests.

Such pull request would be accepted.
