### ISSUE TITLE
flowurl template tag breaks for deleted tasks

### ISSUE THREAD

**Issue by n-zav** [viewflow/viewflow#135]
It sometimes happens that we have to modify the flows that we already have in production and some processes are already done by that time. There are some issues that we have with removing/renaming the tasks that already exist in the flow.

 `{% flowurl %}` template tag like i.e. `{% flowurl task 'assign' user=request.user%}` breaks with `AttributeError 'NoneType' object has no attribute 'get_task_url'` for the tasks that were removed from the flow. [Here](https://github.com/viewflow/viewflow/blob/master/viewflow/templatetags/viewflow.py#L47)  it tries to do `ref.flow_task.get_task_url` and `flow_task` is then `None`.

So every time when we have to remove or rename a node in the flow that is already in production, we have to either leave it in the code with `old_node=flow.End()` or check directly in the template if `task.flow_task` exists. The problem with the second scenario is that we cannot display a proper task name for the task that is gone. `{{ task }}` - is just something like `<Task: <101> - DONE>` and `task.flow_task` is `None`.

**Comment by kmmbvnr** [comment]
The obsolete nodes support added to the pro verison.

Release coming soon.

**Comment by codingjoe** [comment]
@kmmbvnr are there features in the "pro" version that are not in this repository? We no longer use the pro version, since we can't contribute to it.
Please let me know if there is actually any difference in features.

**Comment by codingjoe** [comment]
Regarding that feature, It would be even better to have actual flow revisions, but that is a much bigger change.

**Comment by kmmbvnr** [comment]
Yep. obsolete nodes support is a  pro feature. 

I evaluated the ability to have flow revisions, but decided not to implement it. I didn'n found any resonable usecase when feature revisions could be usefull

**Comment by kmmbvnr** [comment]
Deleted nodes would be handled correctly if you just add an obsolete node definision to your flow.

If there is an active obsolete node, admin now can cancel it from the web interface.

```
class MyFlow(Flow):
    ...
    obsolete = flow.Obsolete()
```

http://docs.viewflow.io/core_concepts.html#flow-migrations
http://docs.viewflow.io/viewflow_flow.html#viewflow.flow.obsolete.Obsolete
