### ISSUE TITLE
public docs

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#136]
Hi @kmmbvnr,

it would be great to have publicly available docs based on latest master and version tags.
We could really need that for `intersphinx` and also to have a browsable reference of the latest development code.

**Comment by kmmbvnr** [comment]
Sorry, that's impossible. Actually the documentation is the most hard part of any library, and most opensource projects doesn't have it at all.

Actually there is a plan to make most of the docs (totorials, extended usage and etc) are closed for non-paid customer.

And btw, having increasing counter of logged-in users motivates me a lot =) No other stats over downloads and github traffic not actually lists the users that are interested enough.

**Comment by codingjoe** [comment]
@kmmbvnr ok. It might be still possible to have a public `intersphinx` docs file tho, but that is clearly a bonus.
Would it be possible to have 2 versions of the docs? "stable" and "latest"
