### ISSUE TITLE
"viewflow.views.list.AllProcessListView" show all the processes of all the users

### ISSUE THREAD

**Issue by CptJason** [viewflow/viewflow#138]
![image](https://cloud.githubusercontent.com/assets/397285/13691377/53318fa4-e773-11e5-9ecb-5725ab31ee98.png)
In official document, It means current user, not all the users.
Did I left out any detail when I used the "viewflow.views.list.AllProcessListView".

**Comment by kmmbvnr** [comment]
If you would like to show all process for all users, you can use django build-in `generic.ListView`

Generally, I think there is no sense to show the processes to the user that not permitted to view them,  so AllProcessListView do the permissions filters and list only processes that current user can view.

@CptJason please stop use the issue tracker as Q&A website, If you have a questions, and pro-support, you can send it me directly. For the open-source support, please open request on the [StackOverflow](http://stackoverflow.com/search?tab=newest&q=django-viewflow)

**Comment by CptJason** [comment]
@kmmbvnr 
![image](https://cloud.githubusercontent.com/assets/397285/13695890/a51aeca0-e79d-11e5-875e-1867db6b7218.png)
In your opinion, "viewflow.views.list.AllProcessListView" just lists all process instances  those are available for current user, but It doesn't , It lists all process instances those are available for all users when one specific user login.WHY?

**Comment by kmmbvnr** [comment]
There is always a single current user logged in into the site. AllProcessListView list all processes available for the `request.user`.

Process is available for the user if and only if the user have `app_label.view_<process_cls>` permission. See - https://github.com/viewflow/viewflow/blob/master/viewflow/managers.py#L13

If user have `helloworld.view_helloworld` permission and no  `shipment.view_shipment` only `HelloWorld` and no `Shipment` processes would be listed to the user.

**Comment by CptJason** [comment]
@kmmbvnr I have to go through all the features of community version before buying the license of Pro version.
So...
