### ISSUE TITLE
How to toggle break point for viewflow?

### ISSUE THREAD

**Issue by guhuajun** [viewflow/viewflow#144]
Hello,

I am using vscode + python extension. It's not a big issue when toggle a break point for StartProcessView.
![viewflow-debug](https://cloud.githubusercontent.com/assets/14121694/15044567/02612aa6-1308-11e6-9031-28663aeae370.png)

But the break point does not hit when debugging If condition. Any hints will be appreciated.
![viewflow-debug-if](https://cloud.githubusercontent.com/assets/14121694/15044699/e3b9e22c-1308-11e6-8f30-046938d76673.png)

**Comment by kmmbvnr** [comment]
Hi.

The breakpoint that you show on If __init__ methods happens on start project. B/c nodes itself are constructed when code is loaded.
