### ISSUE TITLE
How to assign task owner when using DynamicSplit

### ISSUE THREAD

**Issue by guhuajun** [viewflow/viewflow#146]
Greetings,

I am using dynamic split to start multiple approval tasks based on the number of apporvers that specified by end user. Every thing works fine and I can assign owner for these aporval tasks manually. 

But I want to assign owner automatically. It looks like I should do this in DynamicSplitActivation. Am I corrert? I toggle a breakpoint inside activate_next, but nothing happens.

Any hint?

Best Regards,
Greg Gu

**Comment by kmmbvnr** [comment]
Sorry, there is no public support for Viewflow open version. Please use Stackoverflow.

**Comment by guhuajun** [comment]
I see. Thank you anyway.

**Comment by guhuajun** [comment]
Finally, I have the answer. You can define DynamicSplitActivation like following.
Regarding self.process.approver, it's a ManyToManyField.

In my case, following code is executed in celery worker. You can use logging to inspect variable values, but do remeber, the results are printed in celery worker log.

`
class DynamicSplitActivation(AbstractGateActivation):

    def calculate_next(self):
        self._split_count = self.flow_task._task_count_callback(self.process)

    def activate_next(self):
        if self._split_count:
            token_source = Token.split_token_source(self.task.token, self.task.pk)
            for _ in range(self._split_count):
                self.flow_task._next.Assign(self.process.approver.all()[_])
                self.flow_task._next.activate(prev_activation=self, token=next(token_source))
`

**Comment by kmmbvnr** [comment]
That's not optimal solution to hardcode assign logic in activate_next
