### ISSUE TITLE
error: 'NoneType' object has no attribute 'create_node'

### ISSUE THREAD

**Issue by boakley** [viewflow/viewflow#150]
In base,py there is this block of code:

         if node is None and not no_obsolete:
             obsolete_factory = self._nodes_by_name.get('obsolete', None)
             node = obsolete_factory.create_node(name)

It is possible for `obsolete_factory` to be `None`. If that happens, the last line of code will fail with the error `'NoneType' object has no attribute 'create_node'`

I don't know if the bug is in that statement, or if the bug is that it should be impossible for `obsolete_factory` to be `None` if `no_obsolete` is False.

**Comment by kmmbvnr** [comment]
This is still unrecovable error, I've added raise to clarify it.

```diff
+            if obsolete_factory is None:
+                raise FlowRuntimeError('Node {} not found and no `obsolete` node defined'.format(name))
```
