### ISSUE TITLE
add support for application templates

### ISSUE THREAD

**Issue by boakley** [viewflow/viewflow#152]
View flow currently searches the following paths for a task template:

- /_\<app>_/_\<flow>_/_\<task>_.html
- /_\<app>_/_\<flow>_/task.html
- /viewflow/flow/task.html

I think it would be good if viewflow also searched for "task.html" in the app folder; ie:

- /_\<app>_/task.html

This would make it possible to have a site-wide template for tasks without having to create an identical template for every single flow.

**Comment by codingjoe** [comment]
@boakley you can solve this by creating your own `/viewflow/flow/task.html` file. You can create this file any app template folder that is loaded before `viewflow` is loaded. In other words an app that is before `viewflow` in the `INSTALLED_APPS` setting.

This might still be a good enhancement, if the template within the scope of the current app.

**Comment by kmmbvnr** [comment]
I think this is very rare usecase when you can have 2 different but still generic per-app templates. And this could stridently clash with other app templates.

As for any other django apps, `viewflow/task.html` template could be substituted  as usual in the `TEMPLATES['DIRS']` directory.
