### ISSUE TITLE
Feature: Celery Retry

### ISSUE THREAD

**Issue by willseward** [viewflow/viewflow#154]
Is the anyway you could add a `.RetryAfter(callable)` to the celery node? 

At the moment I'm confuse about how the celery task goes from the Error state to the Retry state. It doesn't look like there any automatic process to handle that. Please correct me if I'm wrong.

**Comment by kmmbvnr** [comment]
The `retry` is the action of the `JobActivation` Generally different UI solutions could be implemented to call it.

To make it consistent with other flow actions, same sort of code like [CancelViewMixin](https://github.com/viewflow/viewflow/blob/master/viewflow/mixins.py#L86) need to be added

**Comment by willseward** [comment]
Ok. I see how you can implement it with the UI now. Thanks!

What do you think about checking for a retry flag around here: https://github.com/viewflow/viewflow/blob/master/viewflow/decorators.py#L92 ? I was thinking that if a retry value has been set via `.RetryAfter()`, the task would automatically reschedule itself upon error.

**Comment by kmmbvnr** [comment]
I don't think that it should be in viewflow. Celery have own way to retry the task - http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying

**Comment by willseward** [comment]
Agreed, but viewflow throws an error saying that there is transition from `Error` to `Done` when it is retried via celery. It would be an easy fix to change the task status to `Retry` in the celery task, but you suggest avoiding modifying the state in the task itself because nothing is locked.
