### ISSUE TITLE
HelloWorld example update

### ISSUE THREAD

**Issue by mrechte** [viewflow/viewflow#155]
Please, could you update the example on front page in order to make it consistent with demo source code and Django current version (1.9) ?
Thanks

Also, approving generates:
OSError: [Errno 111] Connection refused
It would be wise to detail a little bit more the tutorial (were are located the mentioned files, do we need to run startapp, etc.).

**Comment by kmmbvnr** [comment]
git version of demos are always matched to the git version of viewflow source code.

You can use corresponding git tag to get demo for stable viewflow release - https://github.com/viewflow/viewflow/tree/903f6c9b29cc1956a78d44da141d3bf24561fbcf
