### ISSUE TITLE
BitBucket login is asking too many permissions

### ISSUE THREAD

**Issue by mrechte** [viewflow/viewflow#156]
Viewflow is asking the following permissions on my account:
Read and modify your account information
Read and modify your repositories' issues
Access your repositories' build pipelines and configure their variables
Read and modify your team's project settings, and read and transfer repositories within your team's projects
Read and modify your repositories and their pull requests
Administer your repositories
Delete your repositories
Read and modify your snippets
Read and modify your team membership information
Read and modify your repositories' webhooks
Read and modify your repositories' wikis

**Comment by kmmbvnr** [comment]
oops ) 

Fixed.
