### ISSUE TITLE
Allow absolute namespaces in {% flowurl %}

### ISSUE THREAD

**Issue by willseward** [viewflow/viewflow#157]
I'm a bit confused about the new explicit namespaces. When using the `flowurl` templatetag, how would one get the url of a task outside of the current namespace?

https://github.com/viewflow/viewflow/blob/master/viewflow/templatetags/viewflow.py#L18

https://github.com/viewflow/viewflow/blob/master/viewflow/templatetags/viewflow.py#L88

I've tried setting the namespace to `None`, providing a `namespace_map`, etc.
 It will always try to append the current namespace to the url name.

`{% flowurl task user=request.user namespace=None namespace_map=namespace_map %}` and `{% flowurl task user=request.user namespace_map=namespace_map %}` throw `'xxx' is not a registered namespace inside '<request namespace>'`.

`{% flowurl task user=request.user namespace=None %}` throws `Reverse for '<task name>' with arguments '()' and keyword arguments '{'process_pk': 102, 'task_pk': 665}' not found. 0 pattern(s) tried: []`.

**Comment by kmmbvnr** [comment]
If namespace is None or not set the `request.resolver_match.namespace` is used.

**Comment by willseward** [comment]
Right. Doesn't this prevent resolving URLs of tasks outside of their own namespace?

**Comment by kmmbvnr** [comment]
Yep, that makes sence to add absolute ns suppport

**Comment by kmmbvnr** [comment]
There are 4 usecases for the `{% flowurl %}` tag

1. Link inside flow view.

    In this case `rerquest.resolver_match.namespace` points to correct flow namespace and `{% flowurl %}` could be used without any parameters

2. Links from list views (ex inbox, queue) like in the viewflow demo

    For this case i'm registering flows as sub-namespace of list views namespace, ex viewflow:helloworld, viewflow:shipment. 

    - `helloworld/urls.py`  have no namespace references.  
    - `frontend/urls.py` includes flows under own namespaces, and have nsmap like `{'hellowold': HelloWorldFlow}`
    - global url config includes `frontend/urls.py` under the `viewflow` namespace

    In this case, the usage of the tag  is following: 
`{% flowurl ... namespace='viewflow' namespace_map=view.nsmap %}`

    The rationally of using relative nsmaps, is not to have full namespace definition in sub-urls.py.
  
3. Links to the specific flow from other views.
     In this case full-qualified namespace could be used:   `{% flowurl ... namespace='viewflow:helloword' %}

4. Links to unknown flow type from other views

   This case is not implemented. It's requires to have absolute nsmap for flows.


I'm closing issue for now. If someone would like to have `Case 4` implemented, please write rationale for them  over `Case 2`
