### ISSUE TITLE
REST Flows support

### ISSUE THREAD

**Issue by kmmbvnr** [viewflow/viewflow#158]

**Comment by kmmbvnr** [comment]
Implemented in PRO. Would be available in the next release. Preview available at http://demo.viewflow.io/workflow/api/#/

**Comment by guhuajun** [comment]
@kmmbvnr For next release, you mean the veiwflow pro? Hope it will be a feature of the public one.

After struggling with "Activation metadata is broken" for a day, I finally find the "private name" of that goblin, "{{ activation.management_form.as_p }}".  ;)

**Comment by kmmbvnr** [comment]
The rule of thumb for APGL version for this repository is to have no 3d party deps, except the django. 3d party libraries have unpredictable release cycle, breaking changes and a different set of django versions support. Keeping compatible with all of that is hard as hell.

The rest interface is dependent from django-rest-framework and would be available only in pro release.

**Comment by guhuajun** [comment]
@kmmbvnr Thanks for updting. I understand all the decisions that you have made. But django-viewflow is the only reliable workflow package for python/django users. Forgive us to ask for more.

**Comment by codingjoe** [comment]
@kmmbvnr any idea when you will release again?

**Comment by kmmbvnr** [comment]
@codingjoe withing two weeks 0.12.0 (without rest actually)

The release was so delayed b/c i want to collect all breaking changes in one version.

**Comment by codingjoe** [comment]
@kmmbvnr cool. Did I miss 0.11.0?  Latest pro version I see is 0.10.0.

**Comment by rhudock** [comment]
Is this fixed?
