### ISSUE TITLE
Documentation seems broken after update

### ISSUE THREAD

**Issue by SVDV** [viewflow/viewflow#163]
I was reading http://docs.viewflow.io/viewflow_flow.html and after accidental page reload seems like most of the content there was removed. Docs update coming?

**Comment by kmmbvnr** [comment]
yeah, the docs would be updated on the next release

**Comment by SVDV** [comment]
Great! Could you, please, clarify how far is the next release?

**Comment by kmmbvnr** [comment]
2-3 weeks i suppose

**Comment by SVDV** [comment]
Cool, thanks
