### ISSUE TITLE
href link to docs website in /README.rst is broken

### ISSUE THREAD

**Issue by jagu2012** [viewflow/viewflow#165]
Just a small one. The 'Read the documentation at' link goes to a page on docs.viewflow.io that no longer exists and is giving a 404 (http://docs.viewflow.io/introduction.html).

Currently the link is:
  Read the documentation at the `http://docs.viewflow.io/ <http://docs.viewflow.io/introduction.html>`_

....should probably be:
  Read the documentation at the `http://docs.viewflow.io/ <http://docs.viewflow.io/>`_

**Comment by jagu2012** [comment]
Added a pull request:

https://github.com/viewflow/viewflow/pull/166

**Comment by kmmbvnr** [comment]
Thanks for pr
