### ISSUE TITLE
use viewflow without django default permission

### ISSUE THREAD

**Issue by Pyiner** [viewflow/viewflow#177]

**Comment by Pyiner** [comment]
Method in `TaskQuerySet` also call `_available_flows` to check user permission for the flow_class.
But,I'm don't want to use django permission in my project,I have own permission.
So,how can I use `viewflow` without `django default permission`? thanks.

```
def _available_flows(flow_classes, user):
    result = []
    for flow_class in flow_classes:
        opts = flow_class.process_class._meta
        view_perm = "{}.view_{}".format(opts.app_label, opts.model_name)
        if user.has_perm(view_perm):
            result.append(flow_class)
    return result
```

**Comment by kmmbvnr** [comment]
Yep,you need to start with Abstract base models and custom manages.

**Comment by variable** [comment]
Just adding my thoughts, we are currently evaluating the library to see if we want to go on the pro version, I am just wondering if there is a way to turn off the "viewflow" part of the permission checking while retaining the rest fo the project to use django model permissions?

I feel overwriting the `has_perm` to disable the permission project wide is a bit hacky.
