### ISSUE TITLE
How do I start another process while the current one is running?

### ISSUE THREAD

**Issue by narnikgamarnikus** [viewflow/viewflow#179]
Hello!
Tell me, how on a certain flow.If Then or Else launch another process.

Let's say I process a "client", and if the client agrees to a deal, I want to automatically create a "deal" process, how is it better to implement it?

Thanks!

**Comment by kmmbvnr** [comment]
Hi, first of all, please use stackoverfloe to ask questions - http://viewflow.io/contacts/

The subprocess funcionality is part of PRO package.
