### ISSUE TITLE
Role based permission

### ISSUE THREAD

**Issue by narnikgamarnikus** [viewflow/viewflow#181]
Sometimes there is a need to divide processes between cities, and then there is not enough object permission.

For example, the call center operator receives calls from 36 cities, and it needs to distribute them between cities.
Naturally, managers from different cities should not see applications from other cities among their applications.

How can this be realized?

**Comment by kmmbvnr** [comment]
Viewflow PRO has support for django-guardian and object-based permissions http://docs.viewflow.io/viewflow_flow_nodes.html#viewflow.flow.View.Permission
