### ISSUE TITLE
Viewflow-pro 1.0.2 with Django 1.11 failing when Prefetch is used

### ISSUE THREAD

**Issue by grunskis** [viewflow/viewflow#187]
We're trying to upgrade to Django 1.11 & viewflow-pro 1.0.2 @thermondo.We're using `prefetch_related` in a lot of places which started to break after upgrading with exceptions like:

```
ValueError: Prefetch querysets cannot use values().
```

I believe the issue was introduced with this commit https://github.com/django/django/commit/7ec330eeb96d0874949eacb8ed1bbb97e11807e1

I did a bit of investigation and found that this patch helps to avoid this failures:

```patch
~/tmp/viewflow$ git diff --patch
diff --git a/viewflow/managers.py b/viewflow/managers.py
index 50ae6a1..dae0430 100644
--- a/viewflow/managers.py
+++ b/viewflow/managers.py
@@ -99,7 +99,7 @@ class ProcessQuerySet(QuerySet):

     def __init__(self, *args, **kwargs):
         super(ProcessQuerySet, self).__init__(*args, **kwargs)
-        if django.VERSION > (1, 8):
+        if django.VERSION > (1, 8) and django.VERSION < (1, 11):
             self._iterable_class = ProcessIterable

     def filter(self, *args, **kwargs):
@@ -169,7 +169,7 @@ class TaskQuerySet(QuerySet):

     def __init__(self, *args, **kwargs):
         super(TaskQuerySet, self).__init__(*args, **kwargs)
-        if django.VERSION > (1, 8):
+        if django.VERSION > (1, 8) and django.VERSION < (1, 11):
             self._iterable_class = TaskIterable

     def filter(self, *args, **kwargs):
```

Another fix could be to use `ModelIterable` instead of  `BaseIterable` as parent class for `ProcessIterable` & `TaskIterable` but not sure if that would work on older Django versions.

Let me know if I can help you more in debugging the issue.

**Comment by kmmbvnr** [comment]
I'll take a look shortly

**Comment by kmmbvnr** [comment]
Sorry, I can't reproduce. Can't you provide a sample use case, where prefetch related is failed?

**Comment by grunskis** [comment]
Ok, thanks for looking into this! Will try to prepare a failing test today...

**Comment by kmmbvnr** [comment]
@grunskis thank you for your help and detailed report!

It seems there is no way to make it works under [django 1.10](https://github.com/django/django/blob/stable/1.10.x/django/db/models/query.py#L1335) But with django 1.8 and django 1.11 prefetch works now.

viewflow-pro 1.0.3 released.
