### ISSUE TITLE
Missing matching query when writing custom views

### ISSUE THREAD

**Issue by nick-lehmann** [viewflow/viewflow#189]
Because of some form manipulations, I had to write custom views and followed the example in the cookbook. When writing in my view

    if request.POST:
        if includeHelper.check_valid():
            process = includeHelper.save()

            request.activation.process = process
            request.activation.done()
            return redirect(get_next_task_url(request, request.activation.process))

I get a "Matching Query does not exist" error. I first thought my includeHelper, which is just a class managing formsets etc., returns a process that can not be saved due to some error in my code. However, when I skip the part that involves `request.activation`

    if request.POST:
        if includeHelper.check_valid():
            process = includeHelper.save()
            return HttpResponse("ok")

it works. Any ideas?

**Comment by kmmbvnr** [comment]
Please, use StackOverflow to ask questions.

**Comment by nick-lehmann** [comment]
[Done](https://stackoverflow.com/questions/45326560/missing-matching-query-when-writing-custom-views)
