### ISSUE TITLE
Flow mixins with `this`

### ISSUE THREAD

**Issue by tdihp** [viewflow/viewflow#191]
It caught me by surprise that a simple flow mixin didn't work with multiple flow classes:

```python
class ReviewFlowMixin(object):
    check_review = (
        flow.If(lambda activation: activation.process.review == 0)
        .Then(this.fix)
        .Else(this.publish)
    )

    publish = (
        flow.Handler(this.make_publish).Next(this.end)
    )

    def make_publish(self, activation):
        activation.process.publish()


@frontend.register
class AFlow(ReviewFlowMixin, Flow):
    # start -> review -> check_review
    pass


@frontend.register
class BFlow(ReviewFlowMixin, Flow):
    # start -> review -> check_review
    pass
```

When publishing `AFlow`, the `BFlow` nodes will show in "Then"/"Else" nodes.

I suspect this is because the metaclass calls `_Resolver._resolve` on nodes, which recursively "resolve" `this`, but since the nodes aren't copied, the later `BFlow` shares `ReviewFlowMixin` nodes with `AFlow`.

My workaround for now is to wrap `ReviewFlowMixin` with a function to get a fresh mixin every call.

BTW what is some other way to reuse some workflow parts?

**Comment by kmmbvnr** [comment]
Sorry, there is no support on the viewflow free-tier.

Please, use StackOverflow to ask questions.
