### ISSUE TITLE
Tasks are not created when serving project with Gunicorn/Python2.7

### ISSUE THREAD

**Issue by drowolath** [viewflow/viewflow#192]
Hi all,

I tested the library with the "Hello world" example and tried to serve it via gunicorn by doing

```
$ gunicorn demo.wsgi
[2017-08-18 17:17:11 +0000] [23134] [INFO] Starting gunicorn 19.7.1
[2017-08-18 17:17:11 +0000] [23134] [INFO] Listening at: http://127.0.0.1:8000 (23134)
[2017-08-18 17:17:11 +0000] [23134] [INFO] Using worker: sync
[2017-08-18 17:17:11 +0000] [23138] [INFO] Booting worker with pid: 23138
```

When I start a new process, it is created but related tasks aren't created at all.

```
>>> from viewflow.models import Process, Task
>>> from helloworld.models import HelloWorldProcess
>>> HelloWorldProcess.objects.all()
<ProcessQuerySet [<HelloWorldProcess: Hello World #1>]>
>>> Process.objects.all()
<ProcessQuerySet [<Process: Hello World #1>]>
>>> Task.objects.all()
<TaskQuerySet []>
```

Am I missing an important point here?
Did anyone successfully deployed a viewflow app within a django project using a WSGI server?

Thanks

**Comment by kmmbvnr** [comment]
How do you start a process?

**Comment by drowolath** [comment]
Note: I use material.frontend.urls

* under /workflow/ I click on the "Add" button, then click on the "Start" button, and fill in the form
* under /workflow/helloworld/helloworld I click on the "Add" button, and fill in the form

Both actions give the same result: the process is started but no tasks are created.

**Comment by kmmbvnr** [comment]
I don't think that the way of deploying code be related somehow.

Can check the helloworld cookbook sample?

https://github.com/viewflow/cookbook/tree/master/helloworld

```
virtualenv --python=python3.6 env
. env/bin/activate
pip install -r requirements.txt
pip install gunicorn whitenoise
./manage.py migrate
./manage.py createsuperuser
gunicorn demo.wsgi
```

**Comment by drowolath** [comment]
Works perfectly with python 3.6 .
The problem persists when using python 2.7 .

**Comment by kmmbvnr** [comment]
Thank you for the report. That's indeed was py2.7 problem
