### ISSUE TITLE
Dynamic User Assignment on node tasks

### ISSUE THREAD

**Issue by Quizart** [viewflow/viewflow#193]
I've set up a workflow with Dynamic Splitting similar to the demo https://github.com/viewflow/viewflow/tree/master/demo/customnode - however, I need to assign each node task to a user specified in the model. I'm not sure how do this, as I can't assign a function or anything to the .Assign() block - it won't accept a this.function or anything, I get:

```
Cannot assign "<viewflow.ThisObject object at 0x0000000003F541D0>": "Task.owner" must be a "User" instance.
```

How can I go about setting up users for dynamic node processes?

My code:

flows.py
```
...
  split_on_task_assignment = (
    DynamicSplit(lambda p: MOCTask.objects.filter(MOC=p.MOC).count())
    .IfNone(this.end)
    .Next(this.task_completion)
  )

  task_completion = (
    flow.View(views.TaskCompletion)
    .Permission('MOC.is_MOC_actor')
    .Assign(this.assign_actors)
    .Next(this.join_on_task_completion)
  )
...
  def assign_actors(self, activation):
    task = MOCTask.objects.filter(MOC=activation.process.MOC, assigned=False).first()
    task.assigned = True
    task.save()
    return User.objects.filter(email=task.assignee).first()
```
nodes.py is identical to the one in the linked example, therefore DynamicSplit is as well.

It successfully splits up the process and runs it multiple times, but I need to assign owners immediately, instead of letting them assign it themselves as normal.

Thanks for the help!

**Comment by kmmbvnr** [comment]
Sorry, there is no support on the viewflow free-tier.

Please, use StackOverflow to ask questions.

http://viewflow.io/contacts/
