### ISSUE TITLE
A signal `task_created` missing

### ISSUE THREAD

**Issue by grunskis** [viewflow/viewflow#194]
There are already some useful signals in Viewflow, but we are currently in need of `task_created`. We want to send an email when a specific task is created and is ready to be worked on and include a direct link to the task in the email.

Would this be something you would consider adding to Viewflow?

**Comment by kmmbvnr** [comment]
Signals usage to integrate your own code with your own code is the anti-pattern.

I don't think that you would like to notify all users about all task creation (even If and End nodes). For user tasks, you can make user notification explicit, by implementing custom viewflow node inherited from View, ex

```
    approve = (
        UserTask(view.MyView)
        .onCreateEmail(template='...', recipients=....)
        .onAutoAssignEmail(template='...')
   )
```
That would provide much more flexibiliy.

**Comment by grunskis** [comment]
@kmmbvnr Thanks, that helps a lot!
