### ISSUE TITLE
import bpmn files 

### ISSUE THREAD

**Issue by molavy** [viewflow/viewflow#195]
is there any ability to import bpmn and automatically generate workflow from bpmn files export designed in bpmn designer and editor apps

**Comment by kmmbvnr** [comment]
The Viewflow PRO has bpm export ability.

There is no BPMN import b/c it could have very few value

**Comment by molavy** [comment]
There some of java workflow engine like Activiti that create workflow from file import
I need one bpmn engine that support import diagram from file in python

**Comment by kmmbvnr** [comment]
Viewflow is not an engine, Viewflow is embeddable library,

If you have an engine that can import a file and execute it, that black box could be written in any language.

**Comment by snickell** [comment]
@kmmbvnr Pardon, we pay for a viewflow pro license (Ceres Imaging), but I'm finding difficulty finding documentation on how to access the "export to BPMN" functionality, could you suggest a link to this documentation?

**Comment by kmmbvnr** [comment]
Hi @snickell 

It works same as svg export

```
python manage.py  flowexport helloworld/flows.HelloWorldFlow --format=bpmn
```

```
python manage.py flowexport --help
usage: manage.py flowexport [-h] [--output OUTPUT] [--process_pk PROCESS]
                            [--format FORMAT] [--version] [-v {0,1,2,3}]
                            [--settings SETTINGS] [--pythonpath PYTHONPATH]
                            [--traceback] [--no-color] [--force-color]
                            [--skip-checks]
                            flow_label

Export flow graph

positional arguments:
  flow_label            Flow label, i.e. app_label/flows.MyFlow

optional arguments:
  -h, --help            show this help message and exit
  --output OUTPUT, -o OUTPUT
                        Render output to a file
  --process_pk PROCESS, -pk PROCESS
                        Draw process instance state
  --format FORMAT       Export format (svg or bpmn)
```
btw, for the pro customers, rvate support over zendesk is also available: http://viewflow.io/contacts/
