### ISSUE TITLE
rest_framework dependency (pro-only)

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#197]
Hi there found a small bug in version 1.1-pro.
If you want to import `viewflow.contrib.celery` it tries to import `viewflow.rest` (line 9).

Besides, why is `rest` not in `contrib`?

Cheers
-Joe

**Comment by kmmbvnr** [comment]
Mm, yeah. Seems you've got updated before I made announce.

That's fixed already in 1.1.0.pro

**Comment by codingjoe** [comment]
cool! thx 👍

**Comment by kmmbvnr** [comment]
>> Besides, why is rest not in contrib?

Mm, yeah, seems I missed that.

But for some people rest is the primary way to go. And even if that approach violates DRY and requires much for efforts for the same functionality they still don't want to consider standard django views + turbolinks as an alternative.

**Comment by codingjoe** [comment]
Ok, I think its a really amazing feature, plus mostly everyone uses DRF if they use Django and have an API ;)
