### ISSUE TITLE
Incomplete WorkFlow processed.

### ISSUE THREAD

**Issue by prafulbagai** [viewflow/viewflow#201]
I've a workflow.

    class WorkFlow1(Flow):
        start = flow.StartFunction(function1) \
            .Next(this.task2)
        task2 = flow.StartFunction(function2) \
            .Next(this.end)
        end = flow.End()
    
    @flow_start_func
    def function1(activation, **kwargs):
        print('Func1 Called.')
        activation.prepare()
        activation.done()
        return activation
    
    @flow_start_func
    def function2(activation, **kwargs):
        print('Func2 Called.')
        activation.prepare()
        activation.done()
        return activation

I am able to run the workflow programmatically using 

    `WorkFlowClass.start.run()`. 

It starts the workflow perfectly, but, does not the completes it. The output of the above snippet is

    Func1 Called

Upon completing Node1(start) of workflow, `task2` is not called. Meaning, only first task of the workflow is called, not the subsequent tasks.  Why? And how can I execute the complete workflow?

**Comment by kmmbvnr** [comment]
https://stackoverflow.com/questions/49026356/django-viewflow-run-the-complete-worflow/49124280#49124280
