### ISSUE TITLE
StartSignal with error "got multiple values for argument 'sender"

### ISSUE THREAD

**Issue by JohanDi** [viewflow/viewflow#203]
When I attempt to use the StartSignal node, Python throws an error "got multiple values for argument 'sender'".

I am using: 
python3.6 
django 1.11.11
viewflow 1.2.2

The error is produced when I create a new Project instance through the python command line, which fires the start node. 

from django.db.models.signals import post_save
from viewflow import flow
from viewflow.base import this, Flow
from viewflow.decorators import flow_start_signal
from . import models

class ProjectFlow(Flow):  

    process_class = models.ProjectProcess   
    start = (flow.StartSignal(post_save, this.start_flow, sender=models.Project).Next(this.end))   
    end = flow.End()   

    @flow_start_signal
    def start_flow(self, activation, **signal_kwargs):
        activation.prepare()
        activation.done()`

class ProjectProcess(Process):

    project = models.ForeignKey(Project, on_delete=models.CASCADE)

**Comment by elcone** [comment]
adding `@staticmethod` to `start_flow` should work, and the first parameter is wrong, it should be `sender`:

```python
@staticmethod
@flow_start_signal
def start_flow(sender, activation, **signal_kwargs):
    activation.prepare()
    activation.done()
```

**Comment by zsergey85** [comment]
I got this error too. I wrote a 'fix_flow_signal' decorator to fix this error:
```python

def fix_flow_signal(func):
    def _wrapper_fix_signal(self, **kwargs):
        kwargs.update({'self': self})
        func(**kwargs)
    return _wrapper_fix_signal


class ExampleFlow(Flow):

    start = (flow.StartSignal(pre_save, this.start_signal_func, sender=MyModel).Next(this.end))
    end = flow.End()

    @fix_flow_signal
    @flow_start_signal
    def start_signal_func(self, activation, **kwargs):
        activation.prepare()
        print('Success')
        activation.done()

```

**Comment by kmmbvnr** [comment]
Closing this, since it should not be relevant for Viewflow 2.x, since since signal nodes was removed
