### ISSUE TITLE
flow.Join is not being respected. 

### ISSUE THREAD

**Issue by vincentwhales** [viewflow/viewflow#204]
I have the following: 

```
@flow.flow_func
def pull_trigger(activation, *args, **kwargs):
    pass


@frontend.register
class MyPizzaFlow(Flow):
    process_class = MyPizzaProcess

    start = (
        flow.Start(CreateProcessView, fields=['content'])
        .Next(this.split_1)
    )

    split_1 = (
        flow.Split()
        .Next(this.order_pizza)
        .Next(this.external_trigger)
    )

    order_pizza = (
        flow.Handler(this.save_content_to_order)
        .Next(this.join_1)
    )

    external_trigger = (
        flow.Function(pull_trigger)
        .Next(this.join_1)
    )

    join_1 = (
        flow.Join()
        .Next(this.take_the_order)
    )

    take_the_order = (
        flow.View(TakeTheOrderView, fields=['table_location'])
        .Next(this.end)
    )

    end = flow.End()

    def save_content_to_order(self, activation):
        order = Order()
        order.content = activation.process.content
        order.save()
        activation.process.order = order
        activation.process.save()
```

This is my workflow: 
1. Create a new Process in the UI. 
1. After assigning to myself and clicking "done" for that task, I see the following tasks in /admin/: 

![image](https://user-images.githubusercontent.com/28204629/38162416-8073831a-3513-11e8-97cf-f808303f8fa9.png)

I believe this is a bug: "Join 1" should not be done because "External Trigger" has not been executed (Even if it's executed, there is no way the process can advance to "Take The Order" given that `pull_trigger` doesn't do anything.) 

So can someone explain why "Join 1" is marked "DONE" immediately after a new process is created?

**Comment by kmmbvnr** [comment]
Yeah, handler is synchronious task that executed immediately and call join even before another task started.

There is no reason to put handler in the parallel branch. Just put it before split.

**Comment by variable** [comment]
What if a handler follows a view? Will it not respect the join?

**Comment by variable** [comment]
I figured that, if the handler paths are defined after the view paths, then they the join is respected.

eg.
```
split = (
        flow.Split()
        .Next(this.form_1)
        .Next(this.form_2)
        .Next(this.handler_1)
        .Next(this.handler_2)
    )
```

**Comment by kmmbvnr** [comment]
That was the problem in viewflow 1.0, and fixed in 2.x
