### ISSUE TITLE
[i18n] "expected string or bytes-like object" during template rendering

### ISSUE THREAD

**Issue by vincentwhales** [viewflow/viewflow#206]
I keep seeing an error being raised at `/viewflow/models.py` line 105 where `Template(self.flow_task.task_result_summary or "").render(Context({`.

To debug, I place the following:
```
print(self.flow_task.task_result_summary)
print(type(self.flow_task.task_result_summary))
```
right before the error is throw. The results are as such:
```
创建实例
<class 'django.utils.functional.lazy.<locals>.__proxy__'>
```

So somehow the `self.flow_task.task_result_summary` is not `string or bytes-like` which is causing this to fail. 

## Edit:

This commit fixes the problem, but I don't know whether this is a good solution: https://github.com/vincentwhales/viewflow/commit/8cc97dd51b1a772c04ba93b9c87390b850a4583f

**Comment by vincentwhales** [comment]
This is the error file:

https://gist.github.com/vincentwhales/35349e030b9bb35445da1a577409b23d

**Comment by vincentwhales** [comment]
Coincidentally, adding this line fixes the issue:

```
    self.template_string = str(self.template_string)
    for match in tag_re.finditer(self.template_string):
```

Is this a desirable solution?

**Comment by codingjoe** [comment]
Hi @vincentwhales it think casing a proxy of a string into a string, is the most suitable solution.
You can also try to use `ugettext`. You only need the lazy (proxy) version, if the code is loaded during module loading.

**Comment by vincentwhales** [comment]
This commit fixes the problem, but I don't know whether this is a good solution: vincentwhales/viewflow@8cc97dd

**Comment by codingjoe** [comment]
That seems reasonable.

**Comment by kmmbvnr** [comment]
@vincentwhales  thanks for noticing and the fix! To be py27 compatible `force_text` should be used instead plain `str` call
