### ISSUE TITLE
How can we pass on objects between tasks without declaring it in models? 

### ISSUE THREAD

**Issue by siddharthk-hashedin** [viewflow/viewflow#210]
Is there any other way to pass on variables between tasks beside using 
``` activation.prepare()
    process.var_name= value
    process.save()
    activation.done()
```
and then accessing it like,
```activation.process.var_name```
limitation with this approach is I have to declare a var_name member in model. I want to escape from declaring new members in model. 
So any approach for passing variables between tasks without using models.

**Comment by kmmbvnr** [comment]
Hi, please use StackOverflow to ask questions http://viewflow.io/contacts

**Comment by siddharthk-hashedin** [comment]
hi,
I have asked it.
