### ISSUE TITLE
Permission checks do not support User subclassing

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#212]
My application implements its own notion of User based on top of the facilities that Django has for doing so. In addition, I have different kinds of Users such as Employees and Administrators. This all works quite well but there is a subtle unfortunate interaction with the permission checking in Viewflow. Specifically, in two places in viewflow/nodes/view.py, a direct equality check is made:

    viewflow/nodes/view.py:103:                return owner == user
    viewflow/nodes/view.py:322:        return task.owner == user

This object to object equality check fails. If these lines were changed to compare only the owner.id/owner_id, then it would solve my problem, and be faster. I note that elsewhere in the file, the owner_id is used, for example just a few lines before the second example above:

    viewflow/nodes/view.py:311:        if task.owner_id == user.pk:

Would you be willing to make this change, or accept a PR for this?

**Comment by kmmbvnr** [comment]
I decided that the current viewflow implementation much safer.

If you need customize that behaviour, you can subclass flow.View node and override the required methods.

**Comment by ShaheedHaque** [comment]
OK. However, I respectfully disagree with your assessment about the current code being "much safer". Firstly, subclassing User is a well documented feature of Django, and as I noted, your own code a few lines away uses exactly the same id comparison logic.
