### ISSUE TITLE
How to cleanly finish a Process with split-n-join tasks?

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#213]
Say I have a Process which has two optional View tasks to the finish:

    --> Split --> optional_view_1 ---> Join ----> finish
           |                            ^
           |                            |
           -----> optional_view_2 -------

Let's say both tasks are assigned, but a human logs in and completes optional_view_1. I want to ensure the Process finishes cleanly.

AFAICS, the Process gets into a "stuck" state due to optional_view_2 at the Join. Is that correct? I tried cancelling optional_view_2, but that had no effect. I'm looking for a programmatic approach if that makes any difference. I'm aware of #93, and so I think my question boils down to:

- how to finish the process cleanly (i.e. not cancel it) and without races
- from where (e.g. from inside the Join or a Handler after each View to cancel the other one?)

What is the correct procedure in this case?

**Comment by ShaheedHaque** [comment]
I forgot to confirm that the Join specified wait_all=False.

    close_join = flow.Join(wait_all=False).Next(this.close_sickness)

**Comment by ShaheedHaque** [comment]
This is what I ended up with:

`

    class Join(vf_flow.Join):
        class CancelAlternateTasksActivation(JoinActivation):
            def done(self):
                if not self.flow_task._wait_all:
                    #
                    # Get rid of any alternate tasks: logic adapted from
                    # super().is_done().
                    #
                    previous = self.task.previous.exclude(status=STATUS.CANCELED).all()
                    join_prefixes = set(prev.token.get_common_split_prefix(self.task.token, prev.pk)
                                        for prev in previous)
                    if len(join_prefixes) > 1:
                        raise FlowRuntimeError('Multiple tokens {} came to join {}'.format(join_prefixes,
                                                                                           self.flow_task.name))
                    #
                    # Don't forget to exclude the previous tasks.
                    #
                    join_token_prefix = next(iter(join_prefixes))
                    active = self.flow_class.task_class._default_manager \
                        .filter(process=self.process, token__startswith=join_token_prefix) \
                        .exclude(status__in=[STATUS.DONE, STATUS.CANCELED], pk__in=[prev.pk for prev in previous])
    
                    def cancel_task(task):
                        """
                        Adopted from https://github.com/viewflow/viewflow/issues/93.
                        """
                        pass
    
                    for task in active:
                        cancel_task(task)
                #
                # The superclass call may end up finishing the process.
                #
                super().done()
    
        activation_class = CancelAlternateTasksActivation   
`

As you can see, I took the bulk of the body from JoinActivation.is_done(), and assuming this looks right, I'd like to confirm two things:

- I'm a little unsure if the logic of `previous` is correcty picking up the predecessor task.
- the main difference between this version and the original which is that I extended the `.exclude()` clause.

**Comment by kmmbvnr** [comment]
In terms of bpnm. The thing that you are looking for is the event-based split gateway, that cancels other parallel  flows, on a first task complete.

In viewflowthat could be implelemented as a custom split node.


For the future, to ask questions, please, don't use issue tracker, and follow guides on http://viewflow.io/contacts
