### ISSUE TITLE
api level tutorial is required

### ISSUE THREAD

**Issue by lazywhite** [viewflow/viewflow#214]
Maybe someone like me need this kind of document
```
# python manage.py shell
>from app.models import DemoProcess
>p = DemoProcess()
>p.start()
>p.approved = True
>p.next()
>p.end()
```

**Comment by kmmbvnr** [comment]
Viewflow is a thin workflow layer on top of Django. There is no puplic API excet `activation` methods


Process is just a Django model, View is just a Django view. No new API introduced.

Foe the future questions please don't use the issue tracker. Follow guide on http://viewflow.io/contacts
