### ISSUE TITLE
Configuring viewflow.io error handling model

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#215]
This is a [cross post](https://stackoverflow.com/questions/50243607/configure-viewflow-io-error-handling-model) of a StackOverflow question..

I noticed that given a sequence of Viewflow Nodes like this:

    A -> B -> C ->... -> W -> X 

a failure in X causes **ALL** Tasks for A through W to be unwound in the sense that the database table for Tasks record only the attempt to start A. All traces of the successful execution of A through W are lost.

From [the docs](http://docs.viewflow.io/viewflow_core_exceptions.html#viewflow.activation.Context) on `Context`, it looks as though using

    with Context(propagate_exception=False):
        activation.done()

the behaviour can be changed to such that A through W are completed, and only Y ends up in an ERROR state. Now, the docs describe this setting as having thread scope, so the question is, how can propagate_exception=False be configured application wide? Or is there a list of Nodes that need to implement Context(propagate_exception=False)?

**Comment by kmmbvnr** [comment]
Hi, this in an issue tracker for viewflow project. If you have any questions, please follow the guideline on http://viewflow.io/contacts
