### ISSUE TITLE
DjangoViewflow - Not executing the complete flow

### ISSUE THREAD

**Issue by prafulbagai** [viewflow/viewflow#216]
I've a workflow consisting of multiple nodes.

    @frontend.register
    class Flow1(Flow):
        process_class = CreationProcess
    
        start = (
            flow.StartFunction(this.create)
            .Next(this.credit_line)
        )
    
        credit_line = (
            flow.Handler(this.cibil)
            .Next(this.seynse_score)
        )
    
        score = (
            flow.Handler(this.seynse)
            .Next(this.score)
        )
    
        check_score = (
            flow.If(lambda activation: activation)
            .Then(this.send_task)
            .Else(this.end)
        )
    
        send_task = (
            flow.Handler(
                this.send
            ).Next(this.end)
        )
    
        end = flow.End()

I run the flow like this:-

    Flow1.start.run()

The problem that I'm facing is that it only runs the start node. The following nodes are not executed. Why?

**Comment by kmmbvnr** [comment]
Generally there is no reason to combine usual synchroniuos function calls adding additional overhead with viewflow, so the case StartFunction-> Handler are not supported.

**Comment by prafulbagai** [comment]
Well, I would like it to be modular. The initiation of the process involves multiple steps(function calls) until the flow reaches a Viewnode. Is there a specific reason why `StartFunction` to `Handler` is not supported when `Handler` to `Handler` and `Viewnode` to `Handler` are supported?

Also, if I need to make some changes to support `StartFunction` to `Handler`, which files should I be looking into?

**Comment by prafulbagai** [comment]
@kmmbvnr - Any lead on this would be very helpful. Thanks.

**Comment by jntsouza** [comment]
This could be in the DOC, I was facing the same problem...
