### ISSUE TITLE
There is no way to globally set the error propagation model

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#218]
As per the docs, a Context object can be used to modify the value of propagate_exception. As per the now-closed #215, there is no way to set this policy globally at the application level or in some other way to ensure that all flows have non-default behaviour (from activation.py):

> context = Context.create(propagate_exception=True)

I would like this to be made configurable. If it might be acceptable, I'd be happy to propose a PR (for example, based on a django.conf setting).

**Comment by kmmbvnr** [comment]
I don't think that it's valuable.

**Comment by ShaheedHaque** [comment]
In that case, can you clarify how to ensure this is set for each flow/thread that needs it?
