### ISSUE TITLE
Question: Inline forms on detail view

### ISSUE THREAD

**Issue by mbaechtold** [viewflow/viewflow#221]
Does `django-viewflow` provide a feature where one could have inline forms on the detail view of an object?

**Comment by mbaechtold** [comment]
Oops, this question should better be placed in https://github.com/viewflow/django-material/

**Comment by kmmbvnr** [comment]
I'm not sure what do you mean. The detail view is the simple template view and could be easily overridden in your code.

Generally questions about Viewflow could be asked on the StackOverflow or zendesk http://viewflow.io/contacts
