### ISSUE TITLE
REST API Does Not Work

### ISSUE THREAD

**Issue by charliecliff** [viewflow/viewflow#222]
Your Rest API Does not work for the Pro Version.

The Example that you have posted here:
http://demo.viewflow.io/workflow/api/#!/hellorest%2Ftasks%2Fstart/viewflow_rest_views_start_CreateProcessView_object_at_0x7ff251339990

Also does not work.

The Curl Command that you preent returns a 403: Permission Denied Error:
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-CSRFToken: liohVMCjr95oEangb4ZNB15oZreIb4FYL8DMLf3xhw1CZ062RRkXg0zh1Ipq9R5r' -d '{ \ 
   "text": "TEST" \ 
 }' 'http://demo.viewflow.io/workflow/api/tasks/hellorest/start/'`

So.
Your Official Example of your paid version literally just DOES NOT work.

So.
Why?

**Comment by kmmbvnr** [comment]
You've got "Permission auth error" b/c didn't send any authentification information in your request.

Demo site configured to use token auth and session auth.
