### ISSUE TITLE
Run Django-Viewflow Update node?

### ISSUE THREAD

**Issue by prafulbagai** [viewflow/viewflow#224]
I'm using django-viewflow to create a workflow programatically.

This is my flow class.

    class APLWorkflow(Flow):
    
        start = (
            flow.StartFunction(function1)
            .Next(this.shipment_create)
        )
    
        shipment_create = (
            flow.Function(function3)
            .Next(this.delivery_mode)
        )
    
        delivery_mode = (
            flow.If(cond=lambda x: 1 > 2)
            .Then(this.check_insurance)
            .Else(this.request_quotes)
        )
    
        request_quotes = (
            flow.Handler(function3)
            .Next(this.join_clerk_warehouse)
        )
    
        check_insurance = (
            flow.Handler(function3)
            .Next(this.fill_post_label)
        )
    
        fill_post_label = (
            flow.Handler(function3)
            .Next(this.join_on_insurance)
        )
    
        join_on_insurance = (
            flow.Join()
            .Next(this.join_clerk_warehouse)
        )
    
        # Warehouse worker
        package_goods = (
            flow.Handler(function3)
            .Next(this.join_clerk_warehouse)
        )
    
        join_clerk_warehouse = (
            flow.Join()
            .Next(this.move_package)
        )
    
        move_package = (
            flow.Function(function3)
            .Next(this.end)
        )
    
        end = flow.End()

What I do is, I start the flow programatically, when a POST request is made onto an endpoint E1, I run

    APLWorkFLow.start.run(**some_kwargs)

It starts correctly, and after the processing of the `start` is completed, then the response is returned back to the client.

Now, `shipment_create` is run when a POST request is made on endpoint E2, and I again run it programmatically via, 

    activation.flow_task.run(**some_kwargs)

It runs correctly and completes the flow upto `move_package`.

**THE PROBLEM**

I update the details of `shipment`, via PUT request on endpoint E3, and I want to rerun the complete flow after node `shipment_create`. How can I do that? 

1) How can I re-run the flow after a specific node?

2) Point(1) is a manual step, ie programatically re-run the after nodes. Is there a way, I can include `shipment_update` node in Workflow class itself, so that it automatically re-runs the after-nodes? How and where I would mention `update_shipment` node?

The problem I see in point(2) is, in one situation I am declaring `shipment_create` node after start (and the rest Handlers will process), and in another situation **I've to** mention `shipment_update` node after start (and the rest Handlers will process). How will the workflow class work according to the type of HTTP method?

**Comment by kmmbvnr** [comment]
Hi, please use StackOverflow to ask questions http://viewflow.io/contacts

**Comment by prafulbagai** [comment]
@kmmbvnr - Kindly respond here. https://stackoverflow.com/questions/51653865/run-django-viewflow-update-node
