### ISSUE TITLE
Can I use Cache on top of viewflow?

### ISSUE THREAD

**Issue by prafulbagai** [viewflow/viewflow#225]
I would like to fork the repository and include cache layer in between the DB layer and the application code. 
What would be the right approach to save `process, task, task_previous` table data to cache before persisting it into DB. Would you even recommend doing?

**Comment by kmmbvnr** [comment]
I don't see reasons to use cache.

**Comment by prafulbagai** [comment]
How about keeping the current and next set of task in memory, instead of reading/writing it from DB?

**Comment by prafulbagai** [comment]
Also, as a general practice I'm keeping my DBs different (workflow DB and application DB). I think it makes sense to have a cache layer on top of Workflow DB to improvise on time efficiency.

**Comment by kmmbvnr** [comment]
Couple viewflow related queries (performed by pk indexes) have no impact on overall website performance.
