### ISSUE TITLE
Can you upload an attachment?

### ISSUE THREAD

**Issue by meatballcoder** [viewflow/viewflow#227]
Is there a way to upload an attachment to a task?

**Comment by codingjoe** [comment]
> Is there a way to upload an attachment to a task?

Hi @meatballcoder there sure is! All you need to do is add a file field to your process model. Make sure to add the field to a ViewTask and users will be able to upload a file.

eg.
```python
from django.db import models
from viewflow.models import AbstractProcess


class FileProcess(AbstractProcess):
    some_file = models.FileField(upload_to='some/path')
```

```python
from viewflow import flow

from . import models


class FileFlow(flow.Flow):
    process_class = models.FileProcess
    # some task nodes
    upload_file = flow.ViewNode(fields=['some_file'])
    # some more task nodes
```

Something like this should do the trick. I didn't test the code there might be some typos, but I hope the general idea is clear.

Best
-joe

**Comment by codingjoe** [comment]
I can not really share production code with you. But the `FileField` works just as any other field perfectly well with viewflow.

**Comment by meatballcoder** [comment]
I got it working.  Sorry about that.  Thanks.
