### ISSUE TITLE
[PRO] DeprecationWarning `inspect.getargspec()` in `test.py`

### ISSUE THREAD

**Issue by amureki** [viewflow/viewflow#230]
Greetings there,

we  recently discovered `DeprecationWarning` coming from viewflow in our test logs:
`viewflow/test.py:175: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()`.
Can we update this code to get rid of this warning?

Python 3.6.6, Django 2.0.9, pytest 3.9.3.

Thank you,
Rustem

**Comment by amureki** [comment]
Hi @kmmbvnr ,

the version is `django-viewflow-pro==1.4.1`

**Comment by kmmbvnr** [comment]
Fixed in 1.5.0
