### ISSUE TITLE
Possible bug in get_flow_namespace(self, flow_class)

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#231]
The code in viewflow.flow.views.mixins.get_flow_namespace() appears to be missing an "else" clause. At the moment (with 1.4.0), the function ends like this:
```
        if not self.ns_map_absolute:
            return "{}:{}".format(self.request.resolver_match.namespace, namespace)
```
I suspect the correct code should be:
```
        if not self.ns_map_absolute:
            return "{}:{}".format(self.request.resolver_match.namespace, namespace)
        else:
            return namespace
```
on the grounds that if the map is supposed to be "absolute", then no prefix is needed?

**Comment by kmmbvnr** [comment]
That's hard to say is there a valid scenario when the proposed else clause happened. It's definitely not the case of default viewflow frontend. Could you provide a sample?

**Comment by ShaheedHaque** [comment]
I don't have a case in point because I came across the code when trying to understand how namespaces and viewflow URLs worked, including the purpose of self.ns_map_absolute. To elaborate, there are two routines by each other:
```
   def get_flow_namespace(self, flow_class):
        namespace = self.ns_map.get(flow_class)
        if namespace is None:
            raise FlowRuntimeError("{} are not registered in {}".format(flow_class, self))
        if not self.ns_map_absolute:
            return "{}:{}".format(self.request.resolver_match.namespace, namespace)

    def get_process_url(self, process, url_type='detail'):
        namespace = self.get_flow_namespace(process.flow_class)
        return reverse('{}:{}'.format(namespace, url_type), args=[process.pk])
```
Here, `get_process_url()` looks as though it is not expecting a `None` result from `get_flow_namespace()` because that would result in a strange looking URL, right? However, if self.ns_map_absolute is True, then that is what will be returned. Now, self.ns_map_absolute is only ever set to False in the code I can see, but if it has any purpose at all, it  is presumably possible to set it to True or False. Hence my suggestion that this might be a bug waiting to strike. 

As to whether the correct `else:` might be to `return namespace`, that is just a guess!
