### ISSUE TITLE
Add support for a event based gateway

### ISSUE THREAD

**Issue by elcone** [viewflow/viewflow#233]
This comes from this [question](https://stackoverflow.com/questions/52311822/how-to-finish-all-parallel-activities-viewflow-terminate-end/53454265#53454265).

What this gateway does, is a parallel activation of the outgoing flows, and when one of the tasks is completed, the others flows are cancelled.

Consider the next diagram:

![imagen](https://user-images.githubusercontent.com/3837395/48963207-1513b980-ef4b-11e8-8986-6d8b2323a5b9.png)

The task **A** is completed, the gateway activates the tasks **B** and **D**, if **B** is completed, **D** is cancelled and the flow continues to **C**, but if **D** is completed before **B**, **B** is cancelled and **C** is never activated and the flow ends.

What is necesary is to create a subclass of the node `Split` with the implementation that you provided in the answer of the question:

```python
class SplitFirst(flow.Split):
    shape = {
        'width': 50,
        'height': 50,
        'svg': """
            <path class="gateway" d="M25,0L50,25L25,50L0,25L25,0"/>
        <text class="gateway-marker" font-size="32px" x="25" y="35">1</text>
        """
    }

    def on_signal(self, sender, **signal_kwargs):
        task = signal_kwargs['task']
        split_first = task.previous.filter(flow_task=self).first()
        if split_first:
            for leading in split_first.leading.all().exclude(pk=task.pk):
                activation = leading.activate()
                if hasattr(activation, 'cancel') and activation.cancel.can_proceed():
                    activation.cancel()

    def ready(self):
        super(SplitFirst, self).ready()

        task_finished.connect(
            self.on_signal,
            sender=self.flow_class,
            dispatch_uid="sample.splitfirst/{}.{}.{}".format(
                self.flow_class.__module__, self.flow_class.__name__, self.name
            )
        )
```

**Comment by kmmbvnr** [comment]
Thank for copy-pasting my code. But generally, I think the specific definition for the node could be located in a user codebase rather than viewflow

**Comment by elcone** [comment]
Even if the node is part of BPMN's core?
