### ISSUE TITLE
Namespace issues if you put your FlowClass inside a submodule

### ISSUE THREAD

**Issue by vincentwhales** [viewflow/viewflow#235]
The example given has recommended to place the `flows.py` file inside your app. In this example, the name of my app is `websites`

```
websites/
├── __init__.py
├── flows.py
```

If you want to have more than 1 flow in your app, it might make sense to do something like this: 
```
websites/
├── __init__.py
├── flows
│   ├── __init__.py
│   └── myflow_class_1.py
│   └── myflow_class_2.py
```

Doing so will break viewflow. In particular, the templatetag [get_url](https://github.com/viewflow/viewflow/blob/385fceb3b486c52d7a7375ca2e738874497cd0c4/viewflow/templatetags/viewflow.py#L48) will complain that _the application 'websites' is not defined in the namespace of 'viewflow'._ 

Is there a way to fix this issue?

**Comment by kmmbvnr** [comment]
Can't reproduce. Probably you forget to list flows in the __init__.py. Same theme as you would do with django models.py

```
helloworld/
    flows/
        __init__.py
            from .hello1 import HelloWorldFlow1
            from .hello2 import HelloWorldFlow2
            __all__ = ( 'HelloWorldFlow1', ' HelloWorldFlow2',)
    hello1.py
       @frontend.register
       class HelloWorldFlow1(Flow):
          ...
    hello2.py
       @frontend.register
       class HelloWorldFlow2(Flow):
          ...
```
