### ISSUE TITLE
How to connect two flows

### ISSUE THREAD

**Issue by everner** [viewflow/viewflow#236]
In order to avoid having huge Flow classes, I'd like to have one flow feed into another. Something like what I have below. Is this possible? Thanks very much. Great library you made...

```
class SecondFlow(Flow):
    process_class = SecondProcess
    start = (...)

class FirstFlow(Flow):
    process_class = FirstProcess
    start = (
        flow.Start(
            CreateProcessView,
            fields=['foo']
        ).Next(SecondFlow.start)
    )
```

**Comment by kmmbvnr** [comment]
Hi, please use StackOverflow to ask questions http://viewflow.io/contacts
