### ISSUE TITLE
ViewFlow Graph

### ISSUE THREAD

**Issue by acantillo14** [viewflow/viewflow#237]
Hi,
I'm trying to implement the view flow library, but I want to know what I'm going to do to run the process graph.

Thank you.

**Comment by acantillo14** [comment]
Hi,
Can not do tests with the free version for the operation of graphics flows?

**Comment by kmmbvnr** [comment]
Viewflow generates a graph from Flows codebase. To evaluate it, there is several demos available, ex: http://demo.viewflow.io/workflow/shipment/shipment/chart.svg/ on the http://demo.viewflow.io/workflow/shipment/shipment/ page
