### ISSUE TITLE
[Question] Correct way of moving task in flow?

### ISSUE THREAD

**Issue by lorenzomorandini** [viewflow/viewflow#238]
As title, is there a correct way of moving a task in the flow? There isn't any problem with already finished processes and with new ones, but what for active processes? Right now I think I would end up with two instanced of the same task.

**Comment by lorenzomorandini** [comment]
I can help with a PR if you can give me an idea. This is a pretty big problem for us, makes it quite impossible to change a flow once in production.

**Comment by kmmbvnr** [comment]
Basically, you don't need many changes in the database if flow changes. Some nodes could be migrated during standard data migration procedure, old/removed nodes could be handled by flow.Obsolete() node.

http://docs.viewflow.io/viewflow_core.html#flow-migration

**Comment by lorenzomorandini** [comment]
Maybe I didn't explain myself, sorry. Assume I have the following flow:
start -> task1 -> task2 -> task3 -> task4 -> end
I have an active process with start=DONE, task1=DONE, task2=ASSIGNED

In flow definition, I move task1 so the new flow is
start -> task2 -> task3 -> task1 -> task4 -> end
Once my active flow completes task3, task1 will be activated again, even if I already completed it.

**Comment by kmmbvnr** [comment]
Mm, yeah, but I think tthere is no way to handle such cases except _explicitly_ provide desired path for existing flows. So your new flow should looks like:

task2 -> task3_old -> task4_old -> end
start -> task2_new -> task3 -> task1 -> task4 -> end

Note that task2 has no incoming edge, so it never would be reactivated again.

**Comment by lorenzomorandini** [comment]
I would prefer to avoid duplicating code for task2. I found a way to skip creating a new task if it has been activated already in the currect process (except JOIN). Would you be interested in review a PR?

**Comment by kmmbvnr** [comment]
I don't like implicit solutions. The goal of viewflow to make execution graph explicit and visible.

Another goal is to provide an easy way to write custom nodes with custom activation logic.

So I think it's pretty legitimate to have sauch node in your codebase, but it should not be located in the core library.
