### ISSUE TITLE
Obsolete node (viewflow-pro) raises RuntimeError on Python 3.7

### ISSUE THREAD

**Issue by wearebasti** [viewflow/viewflow#239]
As far as I can see the linked line raises a `RuntimeError` as the generator runs in a `StopIteration` exception. (https://www.python.org/dev/peps/pep-0479/)

The issue is raised in the `_outgoing()` method and seems to be fixable by changing it to:
```python
    def _outgoing(self):
        return []
```

**Comment by kmmbvnr** [comment]
Thanks for noticing! I made 1.5.2 pro release with the fix.

Replace by::

    def _outgoing(self):
        return
        yield

in order to keep the same type of return value for all _outgoing functions.

**Comment by wearebasti** [comment]
Thank you for the fast solution!
