### ISSUE TITLE
NSubprocess View Error

### ISSUE THREAD

**Issue by ivan-fedorov-probegin** [viewflow/viewflow#242]
there is no subprocess property
`
for subprocess in activation.subprocesses
should be replaced with
for subprocess in activation.subprocesses()
`

**Comment by kmmbvnr** [comment]
Thanks for noticing!

Looks you probably mean one of rest interface serializers.


Fixed in https://github.com/kmmbvnr/viewflow-pro/commit/cf385568a339abde3b17189f1827c9cf72b4cbc8
