### ISSUE TITLE
 'NoneType' object has no attribute 'task_class'

### ISSUE THREAD

**Issue by binooetomo** [viewflow/viewflow#243]
my models.py :

```
class Customer(models.Model) :
    form_number = models.CharField(max_length=20,
        verbose_name='Form Number',
        help_text='Nomor Form')
    name = models.CharField(max_length=40,
        verbose_name='Name',
        help_text='Nama')

    def __str__(self) :
        return self.name

class CustomerProcess(Process) :
    customer = models.ForeignKey(Customer, blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Customer Registration list'
        permissions = [
            ('can_start_request', 'Can start Cust. Registration'),
        ]

class CustomerTask(Task):
    class Meta:
        proxy = True
```
my flows.py :

```
class RegistrationFlow(Flow):
    process_class = CustomerProcess
    task_class = CustomerTask

    start = (
        flow.Start(views.StartView)
        .Permission('customer.can_start_request')
        .Next(flow.End())
    )

frontend.register(RegistrationFlow)

```

I got traceback as :

> Traceback (most recent call last):
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
>     return func(*args, **kwds)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/decorators.py", line 180, in _wrapper
>     return view(request, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/flow/views/start.py", line 57, in dispatch
>     return super(BaseStartFlowMixin, self).dispatch(request, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/views/generic/edit.py", line 194, in post
>     return super().post(request, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
>     return self.form_valid(form)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/flow/views/start.py", line 71, in form_valid
>     self.activation_done(*args, **kwargs)
>   File "/home/bino/asu/vflow02/ofon/erp/views.py", line 21, in activation_done
>     super(StartView, self).activation_done(form)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/flow/views/start.py", line 65, in activation_done
>     self.activation.done()
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 44, in __call__
>     return self.descriptor(self.instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 112, in __call__
>     result = self.func(instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/activation.py", line 288, in done
>     self.activate_next()
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 44, in __call__
>     return self.descriptor(self.instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 112, in __call__
>     result = self.func(instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/activation.py", line 294, in activate_next
>     self.flow_task._next.activate(prev_activation=self, token=self.task.token)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/__init__.py", line 154, in activate
>     return self.activation_class.activate(self, prev_activation, token)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/nodes/handler.py", line 65, in activate
>     activation.perform()
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 44, in __call__
>     return self.descriptor(self.instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 112, in __call__
>     result = self.func(instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/nodes/handler.py", line 34, in perform
>     self.activate_next()
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 44, in __call__
>     return self.descriptor(self.instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/fsm.py", line 112, in __call__
>     result = self.func(instance, *args, **kwargs)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/nodes/handler.py", line 50, in activate_next
>     self.flow_task._next.activate(prev_activation=self, token=self.task.token)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/__init__.py", line 154, in activate
>     return self.activation_class.activate(self, prev_activation, token)
>   File "/home/bino/.local/share/virtualenvs/vflow02-5VctJf20/lib/python3.7/site-packages/viewflow/activation.py", line 785, in activate
>     task = flow_class.task_class(
> AttributeError: 'NoneType' object has no attribute 'task_class'
> [24/May/2019 09:33:56] "POST /workflow/erp/registration/start/?back=%2Fworkflow%2F HTTP/1.1" 500 178700
> 

p.s : this is after I read https://github.com/viewflow/viewflow/issues/171 , but still got same error

**Comment by kmmbvnr** [comment]
`.Next(flow.End())` is completely invalid. You should have separated class attribute for the end task.
