### ISSUE TITLE
ImportError: djangorestframework>3.7 version required 3.10.0 installed

### ISSUE THREAD

**Issue by krerkkiat** [viewflow/viewflow#246]
From your logic to check for the version of the rest_framework that reads `version <= '3.7'` in `__init__.py` line 8

'3.10.0' <= '3.7' is True, but 3.10.0 should be higher than 3.7.

**Comment by kmmbvnr** [comment]
Was fixed at 1.5.9 https://github.com/kmmbvnr/viewflow-pro/commit/bfecb7230d30c8b3a6908f8536f687f926f9013b
