### ISSUE TITLE
Update the start time on task Assign

### ISSUE THREAD

**Issue by nitisha-cb** [viewflow/viewflow#248]
When a user assigns himself a task he's working on, we should set the start time.  
While using the viewflow library, we wanted to build something that auto-unassigns after sometime of no progress on the project, setting the start time should help with auto-unassigning. We noticed there was a similar request (https://github.com/viewflow/viewflow/issues/73).

**Comment by kmmbvnr** [comment]
I've added task.assigned field to avoid confusion with task start time
