### ISSUE TITLE
Is there dynamic workflow creation ?

### ISSUE THREAD

**Issue by simo97** [viewflow/viewflow#250]
Hi am working on a project now and i am looking around to choose a workfow engine, but one of my requirements is to allow users to create worklows dynamically. From what i've seen within the doc viewflow can't handle it. So i just wanted to be sure or there is anthing i am missing ?

**Comment by kmmbvnr** [comment]
In typical application, workflow is only 10%. The rest is forms, models, templates.

Doing all of them dynamicaly leads to completly bypass best of django.
