### ISSUE TITLE
Feature Request: viewflow.templatetags.base.get_model_display_data Options/configuration

### ISSUE THREAD

**Issue by wvisaacswe** [viewflow/viewflow#251]
I would like to see some way to override or modify how the get_model_display_data function in the templatetags module. You could monkey patch the functionality currently but having an extension point for this makes sense to me. If there is a way to do this without monkey patching or changing the source code directly, please let me know.

Here's the use case. We have 1 model called department. We want to reuse it in 2 different flows so we only have to maintain a single list of departments. 

```
class Department(models.Model):
    label = models.CharField(max_length=150)
    def __str__(self):
         return self.label

class CheckRequestProcess(Process):
    text = models.CharField(max_length=150)
    approved = models.BooleanField(default=False)
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
    )

class TimeOffRequestProcess(Process):
    reason = models.CharField(max_length=150)
    approved = models.BooleanField(default=False)
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
    )

```

Since both Process models reference Department, the expand_required() function will grab any requests from from the other Process class that has the same department.  I'd like to either declare a list of models that should be pulled for a given flow or some way to generate the base query for when the templatetag is executed. This feature could be an optional metadata field and default to the way it currently works if not defined.

Here's a [sample project + db](https://github.com/wvisaacswe/viewflow-model-example) that exhibits the issue. Go to an in progress request and see that the other process' models will show up on the right hand side.

**Comment by kmmbvnr** [comment]
I feel that add more features still would not be sufficient.

To change process data, you don't need to tune internal get_model_display_data function

Just create a `templates/[app_name]/[flow_name]/process_data.html` to show any custom model data
