### ISSUE TITLE
Possible to only disable viewflow related permission checking?

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#252]
This is an extension of the previously closed question https://github.com/viewflow/viewflow/issues/177

We are currently evaluating the library to see if we want to go on the pro version, I am just wondering if there is a way to turn off the "viewflow" part of the permission checking while retaining the rest fo the project to use django model permissions?

I feel overwriting the has_perm to disable the permission project wide is a bit hacky.

**Comment by kmmbvnr** [comment]
It's not clear, what do you mean by _"viewflow" part of the permission checking while retaining the rest fo the project to use django model permissions?_

Viewflow uses standard django user class interface and auth backend to check user permissions.

**Comment by variable** [comment]
Hi I understand viewflow uses django permissions, but is it possible to disable that check for viewflow only? I have other apps in the project which also uses default django permissions, but I don't want to manually add per viewflow process permission to existing users and new users when they sign up.

**Comment by kmmbvnr** [comment]
Viewflow does not create permissions, if you don't list them as `.Permission(auto_create=True)`
View model permission exists in Django by default already.

>> add per viewflow process permission to existing users and new users when they sign up.

It's actually pretty common functionality in Django projects. You need to use post_save signal.

**Comment by kmmbvnr** [comment]
But yeah, probably viewflow could be modified to use flow_class.has_view_perm(user) to allow end users to modify view permission check

**Comment by variable** [comment]
> But yeah, probably viewflow could be modified to use flow_class.has_view_perm(user) to allow end users to modify view permission check

Was going to suggest if you can abstract that out to allow overriding.

**Comment by variable** [comment]
Hi @kmmbvnr,

Thanks for making the change, but the change only applies to task permissions, can you please extend to the whole process?

Regards

James

**Comment by kmmbvnr** [comment]
Viewflow 2.x flow classes allows to override has_view_permission and has_manage_permission methods

https://github.com/viewflow/viewflow/blob/main/viewflow/workflow/base.py#L343

Other permission checks are the part of built-in views and flow.View node, that also could be easily overridden
