### ISSUE TITLE
The code on github is not synchronized with demo site

### ISSUE THREAD

**Issue by seamusmore** [viewflow/viewflow#255]
From the [demo web site](http://demo.viewflow.io/workflow/shipment/shipment/list/) we can see there is a filter panel in proccess list view:
![image](https://user-images.githubusercontent.com/35286167/69225807-0db4d980-0bba-11ea-85a9-7a2a06fab512.png)

but the demo code download from github dosen't contain this feature.

**Comment by kmmbvnr** [comment]
Demo shows the viewflow-pro version

**Comment by seamusmore** [comment]
where can I get the pro version?

**Comment by amureki** [comment]
@seamusmore you could find details about pro version here http://viewflow.io/pro/

**Comment by seamusmore** [comment]
> @seamusmore you could find details about pro version here http://viewflow.io/pro/

thanks !
