### ISSUE TITLE
How can I add filter in proccess list view?

### ISSUE THREAD

**Issue by seamusmore** [viewflow/viewflow#256]
I extend a process filter form from django form, and add the form into template "process_list.html".
When I submit filter form I can receive the form data. But the filter form submission will refresh the hole page, and then cause the DataTableMixin submit once more to get json response.  Therefore the filtered data will be replaced with the full data.
How can I make the filter form submit with DataTableMixin together? Or is there other way to add filter for process list view?
Thanks!

**Comment by kmmbvnr** [comment]
The filter enabled by default in the pro package - http://docs.viewflow.io/frontend_crud.html
