### ISSUE TITLE
viewflow-rest requires deprecated django-rest-swagger

### ISSUE THREAD

**Issue by wearebasti** [viewflow/viewflow#264]
As soon as I activate the viewflow-rest module (importing any of it) I get an error because `djang-rest-swagger` is required.

The `django-rest-swagger` seems to be deprecated for 10 Months now, and the last 'change' was made over one year ago. 

Could you please update to something maintained?

Btw.: It would be nice to have the swagger dependency optional.

**Comment by kmmbvnr** [comment]
1.6.1 now does not required swagger by default
