### ISSUE TITLE
_wrapper() missing 2 required positional arguments: 'flow_class' and 'flow_task'

### ISSUE THREAD

**Issue by zgpnuaa** [viewflow/viewflow#267]
I use  django viewflow passing variables to function based view. But when i use decorator  @flow_start_view on view , there is an error :_wrapper() missing 2 required positional arguments: 'flow_class' and 'flow_task'.

**Comment by PekopT** [comment]
same here @kmmbvnr.
как можно починить?

**Comment by kmmbvnr** [comment]
If you don't include Flow.urls but add views directly to your urls config, you need to pass additional flow_class and flow_task url parameters
