### ISSUE TITLE
viewflow.exceptions.FlowRuntimeError: Activation metadata is broken

### ISSUE THREAD

**Issue by neowenshun** [viewflow/viewflow#269]
Hello guys , i have been trying to integrate a e-signature aspect to my django/viewflow project and have faced with this issue . 

The code can be found here : 

[https://stackoverflow.com/questions/61028131/flowruntimeerror-viewflow-django](url)

Could someone help me out here

**Comment by kmmbvnr** [comment]
Please, do no duplicate questions into the issue tracker. If you need a dedicated support, please consider buying PRO package
