### ISSUE TITLE
How to implement a function for users to edit / undo the task 

### ISSUE THREAD

**Issue by neowenshun** [viewflow/viewflow#270]
Is there a way for viewflow to undo or 'edit' a task if they keyed in the wrong value? I understand that there is a way to undo task , however the documentations on that is very minimal , are you all able to assist me ? 

More details of my questions can be found here : 

[https://stackoverflow.com/questions/61073132/how-to-initiate-a-step-back-with-editting-functionality-in-viewflow](url)

I would really really appreciate your help here!

**Comment by kmmbvnr** [comment]
Please, do no duplicate questions into the issue tracker. If you need a dedicated support.
