### ISSUE TITLE
Overriding URL results in error

### ISSUE THREAD

**Issue by neowenshun** [viewflow/viewflow#271]
I overrode the AssignTaskView but it throws off an error : 

Reverse for 'detail' not found. 'detail' is not a valid view function or pattern name.

[https://stackoverflow.com/questions/61097904/correct-way-of-overriding-url-viewflow-reverse-for-detail-not-found-detail](url)

**Comment by kmmbvnr** [comment]
Please, do no duplicate questions into the issue tracker.+
