### ISSUE TITLE
Demo site https

### ISSUE THREAD

**Issue by slavnycoder** [viewflow/viewflow#280]
http://viewflow.io
http://demo.viewflow.io

This sites doesn't have https in 2020. Had some issues with showing your solution for customer.

**Comment by kmmbvnr** [comment]
thanks for the report!

the viewflow v2, gong to have https emabled demo site - https://demo-next.viewflow.io/

**Comment by kmmbvnr** [comment]
Good news, we've got you covered. Both viewflow.io and demo.viewflow.io now have https
