### ISSUE TITLE
FlowTest breaks with python 3.7.8 and >=3.8.0

### ISSUE THREAD

**Issue by syphar** [viewflow/viewflow#281]
When doing python upgrades we discovered what we think is a bug in viewflows `FlowTest` class. 

With python 3.7.8 [this change](https://bugs.python.org/issue40126) was introduced which [changed behaviour in the combination between `mock.patch` as contextmanager](https://github.com/python/cpython/commit/4057e8f9b56789223a1e691d7601003aceb84ad1). 

In our code the error we are seeing here is: 
```
.direnv/python-3.8.3/lib/python3.8/site-packages/viewflow/test.py:213: in __exit__
    patch_manager.__exit__()
        patch_manager = <unittest.mock._patch object at 0x137d3cf70>
        self       = <common.tests.flow_utils.FlowTest object at 0x136dcdca0>
        traceback  = None
        type       = None
        value      = None
../../../.pyenv/versions/3.8.3/lib/python3.8/unittest/mock.py:1524: in __exit__
    return exit_stack.__exit__(*exc_info)
        exc_info   = ()
        exit_stack = <contextlib.ExitStack object at 0x137d5bca0>
        self       = <unittest.mock._patch object at 0x137d3cf70>
../../../.pyenv/versions/3.8.3/lib/python3.8/contextlib.py:483: in __exit__
    received_exc = exc_details[0] is not None
E   IndexError: tuple index out of range
        exc_details = ()
        self       = <contextlib.ExitStack object at 0x137d5bca0> 
```

**Comment by kmmbvnr** [comment]
viewflow/tests.py was deprecated and removed few years ago.

**Comment by syphar** [comment]
@kmmbvnr good to know, I didn't check if it was still there in the open-source version, sorry about that. So this is not an issue here. 

It does still seem to exist in `django-viewflow-pro==1.6.2` though.

**Comment by kmmbvnr** [comment]
Removed in viewflow 1.10.0
