### ISSUE TITLE
  Iterating over process list fails with  Invalid field name(s) given in select_related error

### ISSUE THREAD

**Issue by breneser** [viewflow/viewflow#282]
Hi,

I am having an issue when using an abstract process model with Django and Viewflow.

It looks like Viewflow's process iterator fails if I have a base abstract process.

My use case is as follows:

```python

class MyAbstractProcess(Process):
    class Meta:
         abstract = True

class MyConcreteProcess(MyAbstractProcess):
    pass

```

The error is: `Invalid field name(s) given in select_related: 'myabstractprocess'. Choices are: .... `

I am not entirely sure but I think it comes down to [get_related_path](https://github.com/viewflow/viewflow/blob/de899afdf45540fc5c99691faec292c67758c62d/viewflow/managers.py#L26) code. It seems to be checking for proxy models but abstract Django models doesn't seem to be considered here?

Maybe I am missing something?

Thanks for the help.

**Comment by kmmbvnr** [comment]
Unfortunately, It look to complex to support.

Custom abstract models should be inherited from viewflow.models.AbstractProcess - 
https://github.com/viewflow/viewflow/blob/master/viewflow/models.py#L25
