### ISSUE TITLE
Material frontend + sign to start new processes shows empty list

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#286]
![image](https://user-images.githubusercontent.com/558175/91786198-2c70f200-ec5b-11ea-8e30-7486e71decc9.png)

Just wondering what am I missing?

**Comment by variable** [comment]
OK... after digging through the code, the `Start` node needs to be instance of `flow.Start`,  but in my case, my `Start` node is an instance of `flow.rest.Start` node. Is there a difference between the 2 different Start nodes?

Any chance to get this sorted?

**Comment by kmmbvnr** [comment]
rest.Start provides an API to execute from rest client, whereas frontend works with standard django templates

If you need to start the process from API and from the frontend, two different start handles could be added for the flow class. This would allow you to handle the history of process invocation and distinguish how users triggered the flow.

```
class SampleFlow(Flow):
     start = flow.Start(...).Next(this.second_step)
     api_start = rest.Start(...).Next(this.second_step)
```

**Comment by variable** [comment]
Yep thanks that's what I did as well.
