### ISSUE TITLE
How to integrate formsets into the viewflow node?

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#287]
For example give following models

```python
class NewMobileAPNRequest(Process):
    ....

class AllocatedSimcard(Model):
    parent = ForeignKey(Parent)

TheFormSet = modelformset_factory(AllocatedSimcard, exclude=[])
```

How do I incorporate the formset into say `UpdateProcessView`?

**Comment by variable** [comment]
I suppose I will have to write my own View class since `UpdateProcessView` just extends the django `UpdateView` which does not suppose formsets?

**Comment by variable** [comment]
I have tried to create my own view which extends both `FlowMixin` and `UpdateWithInlinesView` from django-extra-views:

```python
class SimcardInline(InlineFormSetFactory):
    model = AllocatedSimcard
    fields = ['request', 'number']
    factory_kwargs = {'extra': 5}


class UpdateProcessWithInlinesView(FlowMixin, UpdateWithInlinesView):
    model = NewMobileAPNRequest
    inlines = [SimcardInline]
    fields = ['delivery_address']

    def __init__(self, *args, **kwargs):  # noqa D102
        super(UpdateProcessWithInlinesView, self).__init__(*args, **kwargs)

    @property
    def model(self):
        """Process class."""
        return self.activation.flow_class.process_class

    def get_object(self, queryset=None):
        """Return the process for the task activation."""
        return self.activation.process

    def forms_valid(self, *args, **kwargs):
        """If the form is valid, save the associated model and finish the task."""
        super().forms_valid(*args, **kwargs)
        self.activation_done(*args, **kwargs)
        return HttpResponseRedirect(self.get_success_url())
```
While I can enter new simcards, but the `delete` tick boxes are not working as photo:

![image](https://user-images.githubusercontent.com/558175/91914167-86c98b80-ed0b-11ea-9e71-b10f9dfa3ef7.png)

I also tried to use the `material.forms.ModelForm` to create the formset as below, but it didn't make any difference:

```python
class SimcardInlineForm(ModelForm):
    class Meta:
        model = AllocatedSimcard
        fields = ['number']


class SimcardInline(InlineFormSetFactory):
    model = AllocatedSimcard
```

**Comment by kmmbvnr** [comment]
PRO users could use material.forms fields and get inlines inside a usual form without view modifications - http://docs.viewflow.io/forms_formsets.html

or you could write custom functional based view based on the cookbook/custom_views sample

UpdateWithInlinesView is no belongs to this project.

**Comment by variable** [comment]
OK that makes sense, I am a PRO user as well, so don't even need the django-extra-view package

**Comment by variable** [comment]
Got another question
```python
from connect_it.models import NewMobileAPNRequest, AllocatedSimcard
from material.forms import ModelForm, FormSetField
from django.forms import formset_factory


class SimcardInlineForm(ModelForm):
    class Meta:
        model = AllocatedSimcard
        fields = ['number']


class UpdateProcessForm(ModelForm):
    class Meta:
        model = NewMobileAPNRequest
        fields = ['delivery_address']
    simcards = FormSetField(formset_class=formset_factory(SimcardInlineForm, extra=5))
```

flow.py
```python
get_available_simcards = flow.View(frontend_views.UpdateProcessView, form_class=UpdateProcessForm).Next(this.end)
```

I managed to get this UI
![image](https://user-images.githubusercontent.com/558175/91926657-d6b84a80-ed2b-11ea-894e-3fa85cf33fde.png)

But problem is when I save, the simcard records are not being saved, what am I missing?
