### ISSUE TITLE
Adding setUp method

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#290]
Hello, is it possible to add a `setUp()` method to the Flow class that gets called when a workflow instance gets started? Problem I cannot put it inside the `__init__` is that this method gets called when the code gets loaded, eg.

```python
class MyFlow(Flow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # this code gets executed when code being loaded
        # by the FlowMetaClass
        team = Team.objects.get(id=1)
```

Proposing

```python
class MyFlow(Flow):
    def setUp(self, *args, **kwargs):
        team = Team.objects.get(id=1)
```
Normally this will work fine, but if I have to add a field to the Team model, this prevents me able to make migration because it will instantiate the `MyFlow` class in the meta class, and ultimately complain about the new field is missing.

Whilst I can create a custom Start node to achieve this but I think it's more convenient to do it inside `setUp` method so a few similar flows can simply extend on the same base flow class.

An alternative way right now I am using is to create a descriptor class for the team to lazy load:

```python
class LazyTeamLoader():
    """
    Mainly to get around this problem:
    https://github.com/viewflow/viewflow/issues/290
    """
    def __init__(self, team_slug: str):
        self.team_slug = team_slug
        self.team_instance = None

    def __get__(self, *args, **kwargs):
        if self.team_instance:
            return self.team_instance
        return Team.objects.get(slug=self.team_slug)


class MyFlow(Flow):
    iaas_team = LazyTeamLoader('iaas')
```

Let me know what you think?

**Comment by kmmbvnr** [comment]
Looks like descriptor is the legitimate solution.

Basically flow is the  class-based url config, that instantiated as soon as urlpatterns required. Moreover, not all nodes may required external data, the lazy-loading descriptor solves both issues.
