### ISSUE TITLE
[PRO] Material Frontend displays integer 1 and 0 as boolean

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#292]
Not sure if this has been raised before, when I have an integer field in the process model

```
number_of_simcards = models.IntegerField()
```

And if the value is either 1 or 0, the material frontend display the field value as boolean yes/no

![image](https://user-images.githubusercontent.com/558175/94377970-0bc88900-0182-11eb-9c1b-0bee14cec322.png)

**Comment by kmmbvnr** [comment]
Thanks for the report! Default process data template fixed.
