### ISSUE TITLE
[Question] Could flow class object get hold of process instance?

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#293]
I am overwriting the `def has_view_permission(self, user)`, I want this function to return value on condition based on the current active task.

```
def has_view_permission(self, user):
    # PSEUDO
    if process.active_tasks().first().task.flow_task.name == 'pending_on_team_a':
        if user.team == 'team_a':
            return True
```

Is it possible?

**Comment by kmmbvnr** [comment]
Python-code based permissions can't be used in SQL queries, so not suitable for process pagination

To set process-based permission, you need to manually override queryset in the ProcessListView
