### ISSUE TITLE
After following the tutorial, I'm getting a 404 for /workflow/

### ISSUE THREAD

**Issue by 0mars** [viewflow/viewflow#300]
ref: 
http://docs.viewflow.io/viewflow_quickstart.html

```

Request Method: | GET
-- | --
http://127.0.0.1:8000/workflow/



Using the URLconf defined in demo.urls, Django tried these URL patterns, in this order:

    admin/
    ^$
    ^accounts/

The current path, workflow/, didn't match any of these.

```

sorry a django noob here!

thanks

**Comment by kmmbvnr** [comment]
Have you run db migrations after workflow module implementation?

**Comment by 0mars** [comment]
yes!

**Comment by kmmbvnr** [comment]
You need to go to admin and ensure that viewflow frontend module is enabled

/admin/frontend/module/1/change/

**Comment by 0mars** [comment]
404, I have uploaded my demo to, would appreciate it if you have a look
https://github.com/0mars/demo

**Comment by kmmbvnr** [comment]
If you don't have an entry in the admin that mean you didn't run the migrations

**Comment by kmmbvnr** [comment]
and no 'material', and    'material.frontend', in the INSTALLED_APPS

**Comment by 0mars** [comment]
What are the packages needed to be installed, still getting errors if I just installed what's on the tutorial

**Comment by kmmbvnr** [comment]
i'm it's hard to suggest anything else. Check that you have django-material and django-viewflow installed as pakages and in the INSTALLED_APPS and migrations executed

**Comment by 0mars** [comment]
I kept getting module not found, until I installed
django3-viewflow==2.0.2

**Comment by kmmbvnr** [comment]
You need to install django-viewflow and shango-material packages

django3-viewflow package is the scam
