### ISSUE TITLE
Programmatically interact with workflows

### ISSUE THREAD

**Issue by fvitello** [viewflow/viewflow#302]
Hi, 

i want to interact both from the material frontend and from python code with my workflow, in particular with a View. 
The workflow works properly with the material frontend, but i have some problem with programmatically interaction.

I am able to assign the view to an user 
`Task.objects.filter(id=self.kwargs['task_id'])[0].activate().assign(self.request.user)`

but i cannot go ahead with the view. 

The view is defined in the workflow like the following:

`reporting = (
        flow.View(
            viewsets.Reporting,
            task_description='Reporting'
        ).Permission(
            auto_create=True
        ).Next(this.check_operator_accept)
    )`

The model to which the view refers has 2 fields:
` operator_report = CharField(max_length=150)
   operator_accept = BooleanField(default=False)`

How can i  set those fields and go ahead with the workflow steps?
Thanks

**Comment by variable** [comment]
You can try:

```python
activation = Task.objects.filter(id=self.kwargs['task_id'])[0].activate()
activation.assign()
activation.prepare()
activation.done()
```

**Comment by kmmbvnr** [comment]
Nodes that are not executed by a user, is the flow.Function nodes - http://docs.viewflow.io/viewflow_core_node.html#viewflow.nodes.Function
