### ISSUE TITLE
[PRO] How to show lanes on the chart

### ISSUE THREAD

**Issue by pawelkoston** [viewflow/viewflow#304]
I don't know how to generate this fragment of the chart:
![viewflow_pro_lanes](https://user-images.githubusercontent.com/11655309/106265670-a8ca2a00-6227-11eb-9d0c-06afdface4da.jpg)

**Comment by kmmbvnr** [comment]
There is no support for lines in chats.

Since Viewflow allows dynamic roles and permission assignments, including custom callables, I don't think it could be implemented.

**Comment by pawelkoston** [comment]
Thank you for information. It would be nice to put that into the documentation.
