### ISSUE TITLE
How to get hold of the current request.user in CreateProcessView/UpdateProcessView?

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#310]
I would like to automatically set the user field of the process model when a user starts a flow or in update nodes, how do I do that?

**Comment by variable** [comment]
I have only come up with the following, not sure if it's canonical though?

```python
class RequestCreateProcessView(CreateProcessView):
    """
    Sets the user to the saved object
    """
    def form_valid(self, *args, **kwargs):
        result = super().form_valid(*args, **kwargs)
        if result:
            self.object.requester_email = self.request.user.email
            self.object.save()
        return result
```

**Comment by kmmbvnr** [comment]
Viewflow is thin workflow layer on top of standard django Model-View-Template pattern.

Flow views works same as standard django views, just with few addition to call activation.done() method.

All standard django technics applied to flow views as to usual views. Yep `self.request.user` is the right place to go.

https://docs.djangoproject.com/en/3.1/topics/class-based-views/
http://ccbv.co.uk/
