### ISSUE TITLE
Question: How to implement a suspend node?

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#313]
I have a workflow that one of the step is to fire an external API request and return immediately, the request will take time to complete and I want the workflow to suspend after firing the external API request. Normally, we can work it by having a `flow.View` node right after and someone goes back to the workflow and resume the workflow, but in this case, I want the celery worker to poll the result of the external API and resume the workflow automatically.

So in this case, the `flow.View` doesn't seem to fit for purpose, how do I go about creating my own node that waits for invocation?

**Comment by darahsten** [comment]
You could use a flow job, or Customize AbstractNode if you do not have access to the Pro version.

**Comment by variable** [comment]
I have access to Pro version, but flow Job is not exactly what I wanted, I know flow Job dispatches the task into celery worker, but in my case the job can take a long time, I don't want it to take up a celery worker as there are limited number of workers.

**Comment by variable** [comment]
I manage to come up with a workaround by using a `UpdateProcessView` without any fields:

```python
    # Dummy view to hibernate the flow
    # Celery scheduled task will resume this flow once vm clone is finished
    wait_for_clone = flow.View(frontend_views.UpdateProcessView, fields=[]).Next(this.perform_vm_config)
```

Then kick start the workflow again by:

```python
        # advance to next node in viewflow
        activation = vm_request.active_tasks().first().activate()
        activation.assign()
        activation.prepare()
        activation.done()
```

**Comment by darahsten** [comment]
Good that, I think what you needed was a flow.Function which can be called from anywhere to resume the flow. But cudos to that hack.

**Comment by variable** [comment]
I have never understood how to use `flow.Function` in the documentation, can you elaborate a little more please?

**Comment by variable** [comment]
I don't know if using `flow.Function` how I can correlate to the exact "process" instance.

**Comment by variable** [comment]
OK... After digging into the source code and saw the example there, I finally got it.

```python
    wait_for_clone = flow.Function(this.mark_clone_finish).Next(this.perform_vm_config)

    @method_decorator(flow.flow_func)
    def mark_clone_finish(self, activation, **kwargs):
        activation.prepare()
        process = activation.process
        process.clone_finished = True
        process.save()
        activation.done()
```

Then call it by
```python
        # calls the workflow function
        vm_request = NewVMRequest.objects.first()
        task = vm_request.get_task(NewVMRequestFlow.wait_for_clone)
        NewVMRequestFlow.wait_for_clone.run(task=task)
```

**Comment by darahsten** [comment]
Okay, this is fantastic. You got it.
