### ISSUE TITLE
process.save() doesn't work inside handler function

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#314]
I have the following code that saves data to the process instance, but seems the `save()` is not saving to the database, am I missing something obvious? I put some debug code to fetch from database again and it prints the new values.

I logged the sql queries in database, it seems somewhere afterwards is overwriting the process records, but I cannot figure out where

```python
 
    perform_clone = flow.Handler(this.perform_clone_handler).Next(this.end)

    def perform_clone_handler(self, activation):
        """
        Clone template into new VM, first get the new vmid then start the clone process, then save the new vmid for status polling
        """
        process = activation.process
        vm_template = process.proxmox_node.qemu(process.vm_template)
        new_vmid = process.proxmox_api.cluster.nextid.get()     
        process.vm_id = new_vmid
        process.clone_finished = False
        process.save()

        # debug code, it reflects the latest changes
        p = NewVMRequest.objects.get(pk=process.pk)
        print(p.pk, p.vm_id, p.clone_finished)
```

**Comment by kmmbvnr** [comment]
I think, anyway, twice calling save() inside super and overridden method is the anti-pattern in any case. 

Custom form_valid implementation should avoid using super call at all.

Another way to use `updated_fields` to avoid race conditions with data updates - 
https://docs.djangoproject.com/en/3.2/ref/models/instances/#specifying-which-fields-to-save
