### ISSUE TITLE
Question: is it possible to implement my process?

### ISSUE THREAD

**Issue by cfdbwrbq** [viewflow/viewflow#316]
Hi! Thanks for the library. 
is it possible to implement this process (or something similar: scheme all fictional) with viewflow? do i need to buy a __pro__? 
![ticket_draft](https://user-images.githubusercontent.com/12951513/114197864-72153c00-995b-11eb-9b68-04313e20f5d5.png)

_scheme created at [https://storm.bpmn2.ru/](url)_

**Comment by kmmbvnr** [comment]
There is no exception handler, for "work on ticket" task, but t could be modeled with custom node.
