### ISSUE TITLE
[PRO] Question: how ot get old of celery job result

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#318]
Say I have a node that starts a job in an hour

```python
do_work = Job(...).Eta(an_hour).Next(...)
```

How do I have get hold of the result object and revoke it?

https://docs.celeryproject.org/en/stable/getting-started/first-steps-with-celery.html#keeping-results

**Comment by kmmbvnr** [comment]
Hi James, for the pro questions please contact over Zendesk http://viewflow.io/contacts
