### ISSUE TITLE
[Question] Why does the front-end hang on a long-running process

### ISSUE THREAD

**Issue by BrianSidebotham** [viewflow/viewflow#321]
How can I get away from  the front end hanging until a process hits the `end()` node when the process is long-running.

We have some workflows that are pretty much automated, but require quite a few steps that take a long time. When I start these processes with the frontend, it hangs until the entire process completes.

My process is really just using `flow.Handler` nodes.

I imagined that a new thread would kick off the process using the `start` node and the response would be generated and the front end would be usable again. Any ideas where I might be going wrong?

**Comment by kmmbvnr** [comment]
flow.Handler is the task that[ runs synchronously withing previous flow task](http://docs.viewflow.io/viewflow_core_node.html#viewflow.nodes.Handler)

Django itself has no buid-in ways to run task in a background.

Viewflow PRO offres celery.Job to run inside a celery worker - http://docs.viewflow.io/thirdparty_packages_celery.html

**Comment by BrianSidebotham** [comment]
Sure, I'd have said this is one of the first things needed for running workflows.

I've used the `AbstractJobActivation` to implement a threaded activation class for background processing. I was just surprised this wasn't already there as it seems so fundamental.
