### ISSUE TITLE
[Pro feature request?] Allow save and display meta info for each step

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#327]
I have nodes that send out emails to dynamic list of people, whilst I can log who it sent to Graylog, but it's a bit hassle to correlate, is it possible to extend the task model that I can save some meta data and display it on the material frontend?

**Comment by kmmbvnr** [comment]
I could suggest the simplest way to add additional data to a task is to use Task.data json field - https://github.com/viewflow/viewflow/blob/master/viewflow/models.py#L167
