### ISSUE TITLE
When 2.0.0a0 will be released?

### ISSUE THREAD

**Issue by Achilles0509** [viewflow/viewflow#329]
I noticed pre-release version 2.0.0a0 has some great features.
Can you let me know when it will be released?

**Comment by kmmbvnr** [comment]
Hi @Achilles0509, thanks for your interest in the pre-release version 2.0.0a0! 

I'm glad you've noticed the great features it has to offer. As for the release date,  I can't give you an exact date as it depends on a variety of factors. 

However, I've recently published a beta version (2.0.0b1) on PyPI, which  I hope you'll enjoy in the meantime.
