### ISSUE TITLE
Feature request: allow dashboard tile template override for each workflow

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#330]
Can we allow to override the template for each tile in the dashboard?

![image](https://user-images.githubusercontent.com/558175/135169717-cb214b20-ffda-4516-8c54-6eea79c0f040.png)

Eg. I want to display extra fields of the workflow

**Comment by kmmbvnr** [comment]
Dashboard view looks for a template  [<app_label>/<flow_label>/process_dashboard.html,  'viewflow/flow/process_dashboard.html']


So, for the case of the shipment demo, to override a dashboard ``shipment/shipment/process_dashboard.html` need to be created
