### ISSUE TITLE
Bug: when a task is assigned during activation, `assigned` is not set

### ISSUE THREAD

**Issue by longhotsummer** [viewflow/viewflow#331]
When a task is assigned during activation, the `assigned` timestamp is not set. It is set everywhere else when the owner is set/changed/cleared.

In https://github.com/viewflow/viewflow/blob/master/viewflow/flow/activation.py#L88-L92 I believe it should set `task.assigned = now()`.

**Comment by kmmbvnr** [comment]
Thanks for the spot!
