### ISSUE TITLE
(2.0.0a0) Improvements for Django - Suggestion

### ISSUE THREAD

**Issue by christoph-teichmeister** [viewflow/viewflow#335]
Hi @kmmbvnr,

thanks to [this comment](https://github.com/viewflow/django-fsm/issues/267#issuecomment-912257373) we are currently using the pre-release version 2 of this package.

In development, when using this package with Django models, we realised that you were still able to directly alter the field which defines, in which state our model currently is.

<details>
<summary>Quick Example</summary>

```python
class InvoiceStatusChoices(TextChoices):
    NEW = 'NEW', _('New')
    PAID = 'PAID', _('Paid')
    REJECTED = 'REJECTED', _('Rejected')

class Invoice(models.Model):
    status = models.CharField(max_length=150, choices=InvoiceStatusChoices.choices)
```

```python
invoice = Invoice.objects.create()
invoice.status = InvoiceStatusChoices.REJECTED
invoice.save()  # still possible, we wanted to disable this and instead only allow changes via flow transitions
```

</details>

Since we did not want that to be possible, but instead have a developer _always_ call a transition method if he wants to alter the state, we wrote a Mixin, which does not allow state changes to be made directly, but always expects for state changes to happen as a result of having called a transition method.

Do you think its possible for me to create a PR with this mixin, so it can be incorporated in this package? 🙂

**Comment by kmmbvnr** [comment]
I'm glad to hear that you like new viewflow.fsm!

>> a Mixin, which does not allow state changes to be made directly
Could you share details about Mixin implementation? Previous django-fsm approach with custom field descriptor, leads to enormous problems with other django code, like Model.refresh_from_db, model differed attributes, and 3d-party packages like django-model-translation

What do you think just to make a state django field to be private?

https://github.com/vitaly-efremov/django-private-field/blob/master/private_field_meta.py

**Comment by christoph-teichmeister** [comment]
Hey @kmmbvnr,

> Could you share details about Mixin implementation?

Gladly! Our approach is actually similar to django-private-field but does not go as far as renaming the field.

Our "current version" of the Mixin adds a class attribute `protected_fields`, which is a list, in which we specify, which fields will be controlled by a flow.
The Mixin overrides/extends the `.save()` method and checks if, when a `protected_field` is being changed, the `.save()` method was called from a flow. We do this by sending a custom `kwarg` (which can be anything to be honest) to the `.save()` method in the `._on_transition_success()` method of our flow.
If `.save()` tries to alter the value of a `protected_field` _and_ was called from a flow, it allows the change and calls `super().save()`, else it raises a `ValidationError`.

I say "current version of our Mixin" because we recently thought about playing around with custom Fields and overriding their validators, getting rid of our Mixin and just using this custom field for our state field, but we have not gotten around to implementing that yet.

What I personally do not like about `django-private-field` is that it renames the specified fields. I do not think that this is necessary, and, if I understand correctly, it would still allow value changes, which we specifically only want to happen from a flow transition.

Let me know what you think 🙂

**Comment by christoph-teichmeister** [comment]
Hey @kmmbvnr, what's your opinion on this? 🙂

**Comment by kmmbvnr** [comment]
I'm a bit busy right now on other Viewflow parts, I'll return to fsm a bit later

**Comment by GitRon** [comment]
@kmmbvnr Some months have passed. What's the outlook? 🙂

**Comment by kmmbvnr** [comment]
Still working on Viewflow v2

**Comment by kmmbvnr** [comment]
Unfortunately it seems to magical to be in a core library
