### ISSUE TITLE
Compatibility with Django 4.0

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#337]
I noticed a few incompatibilities between Django 4.0 and django-viewflow 1.10.0:

- viewflow/models.py:
  ```
   from django.utils.encoding import force_text
  ```
- viewflow/flow/views/actions.py and viewflow/flow/views/task.py 
  ```
   from django.utils.http import is_safe_url
  ```
- viewflow/management/\_\_init\_\_.py
  ```
    from django.utils.encoding import smart_text
  ```
I'm not sure if there are others, but it would be great to see them fixed.

**Comment by kmmbvnr** [comment]
Thanks for the report!

**Comment by anandrajB** [comment]
am facing error with
from viewflow.fsm import FlowViewsMixin
