### ISSUE TITLE
User approval permit in FSM

### ISSUE THREAD

**Issue by anandrajB** [viewflow/viewflow#338]
hey folks , does django-fsm provides the user approval for a transition ?

for example , 
consider a leave model , a student can apply for a holiday and it should be approved or get rejected by a teacher , who is a staff_user of my system . i'm currently stuck with this FSM concepts :(  , help me to figure this out

**Comment by kmmbvnr** [comment]
If you are using viewflow.fsm you coud check the approval code sample at - https://github.com/viewflow/cookbook/blob/v2/fsm101/review/flows.py

Additional permission information could be added to the transition decorator and checked inside a view - https://docs-next.viewflow.io/fsm/options.html#permissions
