### ISSUE TITLE
[PRO] Using Multiple Flows, Flow starts with wrong Start View

### ISSUE THREAD

**Issue by moonstruck** [viewflow/viewflow#339]
Currently our app has four flows:
```

FlowA(Flow):
    start = Start(FirstView)
FlowB(Flow):
    start = Start(FirstView)
FlowC(Flow):
    start = Start(SecondView)
FlowD(Flow):
    start = Start(SecondView)
```
```python
url(
        "one/",
        include((FlowViewSet(FlowA).urls, "one"), namespace="one"),
    ),
url(
        "two/",
        include((FlowViewSet(FlowB).urls, "two"), namespace="two"),
    ),
url(
        "three/",
        include((FlowViewSet(FlowC).urls, "three"), namespace="three"),
    ),
url(
        "four/",
        include((FlowViewSet(FlowD).urls, "four"), namespace="four"),
    ),
```

Now, 
`http://localhost/three/start` starts with `FirstView` instead of `SecondView`,
`http://localhost/four/start` starts with `FirstView` instead of `SecondView`,

If I comment  `start = Start(FirstView)` on FlowA and FlowB, it starts with SecondView as expected.

Any suggestions how to or where to lookup to sort out this unusual behaviour.

Stay Safe.
Abdullah

**Comment by darahsten** [comment]
It would seem you are using the same process_class for the different flows. I think this is where your problem comes from. Have you tried using different process_classes for each flow.

`class FlowA(Flow):
         process_class = ProcessA
 class FlowB(Flow):
         process_class = ProcessB
 class FlowC(Flow):
         process_class = ProcessC
  .....
  .....
  .....

# if you have to use the same process_class i.e. all of them are attached to ProcessA.
# Then I believe, you can just have different start views/entry points to the process.
# i.e.
 class SampleFlow(Flow):
          start_a = flow.Start(ViewA).Next(view_e)
          start_b = flow.Start(ViewB).Next(view_e)
     .....




`

**Comment by kmmbvnr** [comment]
Can't confirm that.

```python
from django.contrib import admin
from django.urls import path, include
from viewflow.flow.viewset import FlowViewSet
from multiflows import flows


urlpatterns = [
    path("one/", include((FlowViewSet(flows.FlowA).urls, "one"), namespace="one")),
    path("two/", include((FlowViewSet(flows.FlowB).urls, "two"), namespace="two")),
    path("three/", include((FlowViewSet(flows.FlowC).urls, "three"), namespace="thee")),
    path("four/", include((FlowViewSet(flows.FlowD).urls, "four"), namespace="four")),
    path('admin/', admin.site.urls),
]

```

```python
import jsonstore
from viewflow.models import Process as BaseProcess


class Process(BaseProcess):
    field1 = jsonstore.BooleanField(null=True)
    field2 = jsonstore.BooleanField(null=True)
    field3 = jsonstore.BooleanField(null=True)
    field4 = jsonstore.BooleanField(null=True)

    class Meta:
        proxy = True

```

```python
from viewflow import flow, frontend
from viewflow.base import this, Flow
from viewflow.flow import views

from .models import Process


class FlowA(Flow):
    process_class = Process

    start = flow.Start(views.CreateProcessView, fields=['field1']).Next(this.end)
    end = flow.End()


class FlowB(Flow):
    process_class = Process

    start = flow.Start(views.CreateProcessView, fields=['field2']).Next(this.end)
    end = flow.End()


class FlowC(Flow):
    process_class = Process

    start = flow.Start(views.CreateProcessView, fields=['field3']).Next(this.end)
    end = flow.End()


class FlowD(Flow):
    process_class = Process

    start = flow.Start(views.CreateProcessView, fields=['field4']).Next(this.end)
    end = flow.End()

```

Please consider to contact over zendesk to share more project details - https://viewflow.io/contacts

**Comment by moonstruck** [comment]
@darahsten Thanks a lot for suggestions! 
After using different start views/entry points to the process, getting expected behaviour.

**Comment by moonstruck** [comment]
@kmmbvnr As Django proxy models cannot contain fields, do we need to create proxy process model for each task?

**Comment by moonstruck** [comment]
@kmmbvnr Does the flow naming has any effect on url resolution?

In our current scenario:
We have two flow named PayFLow and TokenPayFlow

```python
PayFLow(Flow)
    process_class = PayProcess
    approve = View(SomeView)

TokenPayFlow(Flow):
    process_class = TokenPayProcess
    approve = View(SomeView)
```
Urls:

```python
url(
        "pay/",
        include((FlowViewSet(PayFlow).urls, "pay"), namespace="pay"),
    ),
    url(
        "authorize/",
        include((FlowViewSet(TokenPayFlow).urls, "tokenpay"), namespace="tokenpay"),
    ),
```

Then sending request to 
`{base_url}/tokenpay/<process_pk>/approve` always looks approve taks under PayProcess instead of TokenPayProcess.

But if we change TokenPayFlow to something else that doesn't contain Pay, everything works as expected.

Thanks.

**Comment by darahsten** [comment]
No, there should be no conflict with url resolution. for similarly named tasks in different flows because the flow namespace is include in the URL resolution.
The above setup should not have any problem.
