### ISSUE TITLE
get available transitions 

### ISSUE THREAD

**Issue by anandrajB** [viewflow/viewflow#344]
Hi , am using viewfow.fsm 

how to view the available transition on viewflow fsm when wrapping with django models

**Comment by kmmbvnr** [comment]
I'm hot sure, is the list of available transitions has been implemented yet

You can get list of all transitions by calling the state field method - `get_transitions(self) -> Iterable[Transition]`

**Comment by kmmbvnr** [comment]
Added as:

```python
TheClass.state_field.get_available_transitions(instance, instance.state_field, user)
```

https://github.com/viewflow/viewflow/blob/main/viewflow/workflow/activation.py#L191
