### ISSUE TITLE
Celery setup error: No module named 'viewflow.contrib'

### ISSUE THREAD

**Issue by adamhub** [viewflow/viewflow#354]
Looking at the cookbook implementation of Celery, and the official docs, I keep running into this error from flows.py:

`ModuleNotFoundError: No module named 'viewflow.contrib'`

Using:
- django-viewflow  1.11.0
- celery 4.3.1

flows.py imports:

```
from viewflow import flow
from viewflow import frontend
from viewflow.base import this, Flow
from viewflow.contrib import celery
from viewflow.flow.views import CreateProcessView, UpdateProcessView

from .models import HelloWorldProcess, InsulinProcess
```

**Comment by kmmbvnr** [comment]
http://docs.viewflow.io/thirdparty_packages_celery.html

Celery is part of Viewflow PRO only
