### ISSUE TITLE
Re-open to go back to specific node

### ISSUE THREAD

**Issue by mmartinezd** [viewflow/viewflow#357]
Hi, we're encountering an use case for our workflows that will require that some closed processes are "re-open" and "go back" to an specific node in our flow and continue from that point.
is it possible to implement this?

**Comment by kmmbvnr** [comment]
The practice of the BPMN approach is to explicitly handle this case in a flow.

Please, for the further questions, use StackOverflow or private support for commercial users - http://viewflow.io/contacts/
