### ISSUE TITLE
Generate BPMN Diagram from Flows?

### ISSUE THREAD

**Issue by PeteLambert89** [viewflow/viewflow#362]
Is it possible to generate BPMN diagrams from flows? In the demo project Flows have nice diagrams, but I can't figure out how to do this in the documentation or codebase.

Thanks!

**Comment by kmmbvnr** [comment]
Yep, Viewflow generates bpmn diagrams from the code, It's the PRO version feature only. PRO user could contact over the helpdesk for code samples.

http://viewflow.io/contacts
