### ISSUE TITLE
Viewflow 2.0 - font size in desktop mode too large

### ISSUE THREAD

**Issue by andychoi** [viewflow/viewflow#370]
I think font size in desktop mode is too large.
Is there a way to set default font size and make all others relative to it?

**Comment by kmmbvnr** [comment]
Yep, Material design actually quite larger and leaves mode space than bootstrap-like designs

Viewflow based on the google material-web-components implementation. And in future going to migrate from own custom web components to the standard wrappers are designed by google right now

So this feature would belongs rather to google design implementation. And it looks the issue should be addressed to the google design team https://github.com/material-components/material-web
