### ISSUE TITLE
Django (v4.1) ManifestStaticFilesStorage throws error in combinaton with viewflow (v2.0.0.b1)

### ISSUE THREAD

**Issue by chreichelt** [viewflow/viewflow#374]
I wrote an issue a few months ago when I had a problem with material (v1.11.2) in combination with django(v4.1) https://github.com/viewflow/django-material/issues/527. Now I have the same issue with viewflow.
```python
raise ValueError(
ValueError: The file 'viewflow/js/contrib/dash/dash_table/bundle.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f0207a87610>
```
I reworked my example repository: 
https://gitlab.hrz.tu-chemnitz.de/chre029b--tu-dresden.de/django_test.git

**Comment by kmmbvnr** [comment]
Thank you for the notice, I think i fixed this in the git version. I'll verify and release it soon

**Comment by sewies** [comment]
Hi,

any update on this, @kmmbvnr? Our Django update is blocked due to this issue.

**Comment by kmmbvnr** [comment]
@sewies should be fixed already. Have you have a chance to try v2.0.0.b2 ?
