### ISSUE TITLE
Add https to 1.x series documentation

### ISSUE THREAD

**Issue by longhotsummer** [viewflow/viewflow#375]
Hello,

Thanks for Viewflow, it's great. The documentation for the 1.x series seems to be missing while you're working on the 2.x series. Is it possible to get [docs.viewflow.io ](https://docs.viewflow.io/) back in the mean time?

Thanks!

**Comment by longhotsummer** [comment]
If anyone else is looking, it seems the old docs are available here: http://docs.viewflow.io/index.html (note http not httpS)

**Comment by kmmbvnr** [comment]
Yep, thank you for the notice

There was newer https on v1 docs, I would add it as soon as it would be replaced be v2 docs

**Comment by kmmbvnr** [comment]
old docs are available now at https://v1-docs.viewflow.io/
