### ISSUE TITLE
relation "viewflow_base_task" does not exist

### ISSUE THREAD

**Issue by matlads** [viewflow/viewflow#379]
```
ProgrammingError at /pizza/

relation "viewflow_base_task" does not exist
LINE 1: ..."viewflow_base_process"."artifact_object_id" FROM "viewflow_...
```

i get this after following all the steps in the `README.md`

how do i proceed after here?

**Comment by kmmbvnr** [comment]
I've fixed the tutorial, the missing step was adding `viewflow.workflow` to the INSTALLED_APPS

**Comment by matlads** [comment]
dp you have a commit hash?

**Comment by kmmbvnr** [comment]
Seems i fixed only docs at https://docs-next.viewflow.io/workflow/quick_start.html

Could you point me please, is your issue was resolved by adding `viewflow.workflow` to the INSTALLED_APPS?

**Comment by matlads** [comment]
i confirm that adding `viewflow.workflow` to `INSTALLED_APPS` resolves the problem
