### ISSUE TITLE
ListView initial filter support

### ISSUE THREAD

**Issue by kmmbvnr** [viewflow/viewflow#381]

**Comment by kmmbvnr** [comment]
No support for that in the django-filters

https://github.com/carltongibson/django-filter/issues/322

**Comment by kmmbvnr** [comment]
Added in 34a23922596d6a97e7fb31d810f8507058a55f2d

https://demo.viewflow.io/atlas/sea/

**Comment by SamuelLayNZ** [comment]
Hey I've gotten this working and works pretty well however running into an issue when using multi-choice filters on multiple pages.

Here's two examples:
Type is a charfield on a model with choices set.
On the list view I have
`filterset_initial = {"type": [1, 2, 7, 8, 9]}`
![image](https://github.com/viewflow/viewflow/assets/36492073/45a01b94-da60-4dcc-b45e-f182689da48d)

Second example is a foreign key field on a model
`filterset_initial = {"status": ["1", "2"]}`
![image](https://github.com/viewflow/viewflow/assets/36492073/73d2a3b3-1bb1-48a8-bd87-ee78a8143321)

These filterset_initial settings work fine when you first load the list and work fine on other pages as long as you click filter first.
But if you go straight to the second page with just the initial filters (or even back to the first page with ?page=1) it ignores your initial filters and gives those errors.

May be an issue to be worked out or maybe I'm doing it wrong, let me know!
