### ISSUE TITLE
SytanxError in viewflow/workflow/flow/views/list.py

### ISSUE THREAD

**Issue by tayyabmujahid** [viewflow/viewflow#382]
```
  File "/home/mujahid/PycharmProjects/virtual_envs/django_workflow/lib/python3.7/site-packages/viewflow/workflow/flow/views/list.py", line 133
    if (start_nodes := flow_class.get_start_nodes(self.request.user))

```
im getting a syntaxerror when i import FlowAppViewset.
There seems to be a syntax error in the method definition of flows_start_nodes

**Comment by kmmbvnr** [comment]
It appears that you are encountering a syntax error in the method definition of flows_start_nodes. The issue stems from the use of the walrus operator :=, which was introduced in Python 3.8. As per the Viewflow documentation, version 2.x is designed to work with Python 3.8 or later.

If your project requires Python 3.7, you may consider using Viewflow 1.x instead, as it is compatible with that version of Python
