### ISSUE TITLE
Reloading a form with a file/image input tries to set the value which isn't allowed

### ISSUE THREAD

**Issue by jturmel** [viewflow/viewflow#389]
<img width="349" alt="CleanShot 2023-08-22 at 01 15 45@2x" src="https://github.com/viewflow/viewflow/assets/37833/5da5fbc5-4aff-4ead-a715-6cd449f29763">

Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

**Comment by jturmel** [comment]
This should probably behave like the Django Admin file/image input field where if there is a value, it shows the stored portion of the filename/ext with a link to open it up and view whatever file/image that is, and a checkbox to clear. That way if you're editing a record you don't have to always supply the image/file.

Right now we have to provide an initial value of empty string just so the default widget/form doesn't cause the browser to throw an error and then not render the widget.

cc @kmmbvnr

**Comment by kmmbvnr** [comment]
Fixed in the latest release. Now it sets only text value without changing underline file filed
