### ISSUE TITLE
Calendar widget is off-by-one from the current value

### ISSUE THREAD

**Issue by jturmel** [viewflow/viewflow#392]
Reproduce:

- Use a date field (or date-time field) with the date calendar widget
- Choose a date
- Re-open calendar to change date, notice date selected in calendar is field's date minus 1 day

<img width="601" alt="CleanShot 2023-08-30 at 13 12 04@2x" src="https://github.com/viewflow/viewflow/assets/37833/45c3ea71-2c92-4b7b-8d72-45eafce44bcc">

**Comment by kmmbvnr** [comment]
I tried to reproduce this , but without success

**Comment by jturmel** [comment]
Set your timezone to a negative offset timezone so like US/Central or America/Chicago and then do it.

I can reproduce in my app and the demos.

**Comment by jturmel** [comment]
Any chance of getting this one fixed?

**Comment by kmmbvnr** [comment]
Yep it would be available in the September release

**Comment by kmmbvnr** [comment]
Just released ==2.0.0b8 with the fix
