### ISSUE TITLE
List View Boolean Field Icon

### ISSUE THREAD

**Issue by SamuelLayNZ** [viewflow/viewflow#395]
![image](https://github.com/viewflow/viewflow/assets/36492073/f71070f5-fe92-4b4c-92ba-ebf94b871d16)

Currently check boxes are used to represent boolean values. This is confusing as they look like they can be ticked by the user, like the check boxes on the very left can be.

I suggest switching these to different icons like in V1. These are the ones I chose for my modification.

```
# list.py
    def format_value(self, obj, value):
        if getattr(self.model_field, "flatchoices", None):
            return dict(self.model_field.flatchoices).get(value, "")
        elif isinstance(self.model_field, ModelFieldColumn.BOOLEAN_FIELD_TYPES):
            if value is None:
                return Icon("check_indeterminate_small")
            elif value is True:
                return Icon("check")
            else:
                return Icon("close")
        else:
            return super().format_value(obj, value)
```

**Comment by jturmel** [comment]
I've thought the same. Similar to how Django Admin handles it, it lets you know whether it's on/off but doesn't confuse it with the actual form control itself.

**Comment by kmmbvnr** [comment]
Thanks for the suggestion! Let me think about it.

In the meantime, as you mentioned, this can be done by overriding the format_value method. Viewflow's aim isn't a one-size-fits-all interface but to let users easily tailor parts to their needs. Customizing Viewflow usually means having your base classes and building a solution on top them.

**Comment by kmmbvnr** [comment]
Changed in 8a31c6a99c30adad717dd8fb51eac43b6e0b606c
