### ISSUE TITLE
How to reverse url for a certain task

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#396]
I need to implement a custom search view for the admin, the result needs display the pending tasks and link them.

I tried to use the `flowurl` template tag

`{% flowurl task 'detail' user=request.user%}` but it's complaining NoReverseMatch

`Reverse for 'external_task_installation__detail' not found`

However, this url definitely exists if I go into the right path of site, I presume it loads the urls only at certain point?

![image](https://github.com/viewflow/viewflow/assets/558175/c57dd329-7bd5-4108-bd69-dec0ceb4a203)

**Comment by variable** [comment]
It appears that I was missing the namespace param, if I manually specify the `ns` param eg. `{% flowurl task 'detail' user=request.user ns='my-custom-project' %}` then it would work.

**Comment by kmmbvnr** [comment]
In Viewflow 2.0, URL handling has been generalized, and everything is now treated as a Viewset. This means we use class-based URL configurations to combine multiple views together. Each Viewset has a `.reverse()` method to generate a URL for a view inside it.

Flow Tasks are also treated as viewsets. Within the template, you can use the `{% reverse viewset 'viewname' *args %}` URL tag. 

For example:

```python
  {% reverse request.activation.task.flow_task 'index' process.pk activation.task.pk %}
```
