### ISSUE TITLE
"No transition from DONE" exception from the flow_job decorator

### ISSUE THREAD

**Issue by dmprav** [viewflow/viewflow#397]
Hello!

From time to time, we get `TransitionNotAllowed("No transition from DONE")`  exception from the `flow_job` decorator. (Parts of) the stack trace:

```
viewflow/fsm.py in __call__ at line 103
viewflow/fsm.py in __call__ at line 44
viewflow/decorators.py in _wrapper at line 95
```

Seems like it could be avoided if we change [this](https://github.com/viewflow/viewflow/blob/1.11.0/viewflow/decorators.py#L83) to `if task.status in (STATUS.CANCELED, STATUS.DONE):`. Is this possible?

We use `django-viewflow-pro == 1.11.3`.

**Comment by kmmbvnr** [comment]
Do you need a new release for 1.11.x?

**Comment by dmprav** [comment]
Yes, that would be nice!

**Comment by kmmbvnr** [comment]
I've release 1.11.4 with the fix

For PRO requests there is help desk available at https://viewflow.io/#contactus
