### ISSUE TITLE
Is 2.0.0b1+ going to be released to pypi.org, or considered production ready?

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#398]
Hi,

We are getting messages like this in our logs:

```
/.../python3.11/site-packages/jsonstore/__init__.py:21: UserWarning: The package was merged into django-viewflow. Please consider to switch to django-viewflow>=2.0.0b1
  warnings.warn("The package was merged into django-viewflow. Please consider to switch to django-viewflow>=2.0.0b1")
```

However, when we use pip to `install -U --upgrade-strategy=eager`, Viewflow is NOT being upgraded. I think this is because I don't see anything beyond 1.11 on pypi.org. Is there a plan to upload a newer version at some point?

If not, it would be helpful to know if 2.0.0b1 is considered tested/production ready, so we could install directly from github.

Thanks

**Comment by jturmel** [comment]
It's not a direct upgrade to the 1.x series.

We are running it in production, but it's also not for a mission critical app, important but if we have minor bugs here and there it's not the end of the world, but I'm sure @kmmbvnr can chime in with more info on how close it is to being out of beta.

**Comment by ShaheedHaque** [comment]
@jturmel Thanks for the heads-up.

**Comment by kmmbvnr** [comment]
All viewflow 2.x versions are available on pypi https://pypi.org/project/django-viewflow/#history and could be installed with --pre flag

As for the jsonstore part, it's the improved since last django-jsonstore release, so the viewflow.jsonstore are proffered over django-jsonstore project

**Comment by ShaheedHaque** [comment]
OK, so if we are not using jsonstore today, am I right in thinking 2.x would work for us without any known issue?

(Also, thanks for the information about --pre, but it's not really usable for us. I will instead play with "viewflow>2.0" or something)
