### ISSUE TITLE
django-material to django-viewflow switching

### ISSUE THREAD

**Issue by gwanghyeongim** [viewflow/viewflow#400]
Allow me to ask this here since I'm not sure where else I should. If I'm duplicating this issue, please let me know.

My question is this:
**Is there a guide for seamless transition from django-material to django-viewflow?**

I have a project that heavily uses django-material, precursor of django-viewflow. (amazing library BTW)

The version of django-material is 1.12, which is the latest so far.

Since django-material is not maintained anymore, whenever I run django-admin command such as `runserver`, I see warning like this.

```
UserWarning: The package was merged into django-viewflow. Please consider to switch to django-viewflow>=2.0.0b1
  warnings.warn("The package was merged into django-viewflow. Please consider to switch to django-viewflow>=2.0.0b1")
```

The thing is, I would love to do that. But I don't know where to start. I fear clunky transition might break my project.

So I'd like to know if there is any guide for transition from material to viewflow.

Thanks!

**Comment by kmmbvnr** [comment]
I've put together a basic migration guide on our wiki here: https://github.com/viewflow/viewflow/wiki/Django%E2%80%90Material-and-Viewflow-1.x-migration-Guide. It's a good place to start, though it might not cover everything just yet. If you have any questions or notice anything missing, feel free to drop a message in our GitHub discussions.

**Comment by HappyManRus** [comment]
Hello!
In front I use "{% include 'material/includes/material_css.html' %}"
How is it replaced in Viewflow?

(I tried using viewflow/includes/viewflow_css.html, but it killed my layouts.)

**Comment by HappyManWorld** [comment]
Fix with code:
<link href="{% static 'material/css/materialize.frontend.min.css' %}" rel="stylesheet">
