### ISSUE TITLE
OSError during the quick start example

### ISSUE THREAD

**Issue by matg41** [viewflow/viewflow#409]
Hello
I am following the quick start examples and trying to run BPMN section. The runserver command runs with no error but when I create a new message and try to assign it the following error comes up:

OSError
       at /sample/helloworld/4/approve/13/assign/
  [Errno 22] Invalid argument: 'Quick start\\venv\\Lib\\site-packages\\viewflow\\templates\\viewflow\\workflow\\&lt;property object at 0x0000023A5622E1D0&gt;\\&lt;property object at 0x0000023A5622E220&gt;\\process_data.html'
  
Request Method: | GET
http://127.0.0.1:8000/sample/helloworld/4/approve/13/assign/
4.2.9
OSError
[Errno 22] Invalid argument: 'Quick start\\venv\\Lib\\site-packages\\viewflow\\templates\\viewflow\\workflow\\<property object at 0x0000023A5622E1D0>\\<property object at 0x0000023A5622E220>\\process_data.html'
Quick start\venv\lib\site-packages\django\template\loaders\filesystem.py, line 22, in get_contents
viewflow.workflow.flow.views.actions.AssignTaskView
Quick start\venv\Scripts\python.exe
3.8.8

Thanks

**Comment by viggod** [comment]
I get the same error.

**Comment by kmmbvnr** [comment]
Thank you for the report, that cased by an issue in a custom template path

Fixed in 44a8384bb0c48dec1944e56c1b5ab4ecf92e79e2
