### ISSUE TITLE
Cancelling a single path task does not cancel the full process.

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#412]
If a node in a single path has been 'cancelled', shouldn't the process be cancelled as well? Currently it stays in NEW status.

![image](https://github.com/viewflow/viewflow/assets/558175/fd821581-5105-4ffd-a96a-186d35b27641)

**Comment by kmmbvnr** [comment]
It's a point of decision. At this step you could revive the cancelled task again, cancel whole process, or one or more undo completed task one by one, possible with attached associated undo actions.

**Comment by variable** [comment]
> It's a point of decision. At this step you could revive the cancelled task again, cancel whole process, or undo one or more completed task one by one, possible with attached associated undo actions.

How do I cancel the whole process at this point? It seems there is no way to do it on the UI.

**Comment by kmmbvnr** [comment]
The is a cancel button on the screen
