### ISSUE TITLE
viewflow with dropdown list

### ISSUE THREAD

**Issue by D0wn3r** [viewflow/viewflow#413]
Hi !
I don't have the pro version of your package, so I would like to understand how to use custom forms from Django that can modify variables in the workflow process facilitated by your package. The goal is to make a workflow with a drop-down list.
I'm a newbie in Django.

Best regards !

**Comment by kmmbvnr** [comment]
Viewflow is the thin workflow layer on top of the standard Django models/views/forms and templates

Consider to learn Django forms docs https://docs.djangoproject.com/en/5.0/topics/forms/ and django class-based views docs https://docs.djangoproject.com/en/5.0/topics/class-based-views/generic-editing/
