### ISSUE TITLE
JS are missing

### ISSUE THREAD

**Issue by D0wn3r** [viewflow/viewflow#419]
Hi !
I'm trying to make dashboard with viewflow but js are missing. What happening ? My statics are well collected
Is that only in the paid version of your package ?
![Screenshot 2024-02-26 113123](https://github.com/viewflow/viewflow/assets/87174125/e52bafa7-471f-483a-a8d9-5d1321dc9bab)

Best Regards !

**Comment by kmmbvnr** [comment]
Le't me check, probably some parts missed in the oss version
