### ISSUE TITLE
Bug with dashboard

### ISSUE THREAD

**Issue by D0wn3r** [viewflow/viewflow#421]
Hi,
It's me again ! I'm trying to make a simple dashboard to understand how it works so I'm using your example from documentation:
https://docs.viewflow.io/dashboard/index.html
But this doesn't work. First I had to add the import of User model of Django + timezone from django.utils but it still doesn't work.

dashboard.py:
```python
from dash import dcc
from dash.dependencies import Output
from viewflow.contrib.plotly import Dashboard, material
from django.contrib.auth.models import User
from django.utils import timezone


viewflowDashboard = Dashboard(
    title='Viewflow Demo Stats',
    app_name='vf_stats',
    dashboard_template_name='viewflow/contrib/plotly.html',
    layout=material.PageGrid([
        dcc.Interval(
            id='interval-component',
            interval=2500, # in milliseconds
            n_intervals=0
        ),
        material.InnerRow([
            material.Span4([
                material.Card(
                    value_id='id_active_users',
                    title='Active Users',
                    icon='person'
                )
            ]),
        ])
    ])
)

@viewflowDashboard.callback(Output('id_active_users', 'children'))
def update_active_users(n):
    today = timezone.now().date()
    active_users = User.objects.filter(last_login__date=today).count()
    return active_users
```
    
url.py:
```python
from django.contrib import admin
#### TEST DASHBOARD ####

from django.urls import path
from viewflow.contrib.auth import AuthViewset
from viewflow.urls import Application, Site, ModelViewset
from viewflow.workflow.flow import FlowAppViewset
from sixadmin.dashboard import viewflowDashboard

site = Site(
    title="Workflow 101 Demo",
    primary_color="#01579b",
    secondary_color="#0097a7",
    viewsets=[
        Application(
            app_name="Reports",
            ###icon=Icon("account_balance"),
            menu_template_name=None,
            viewsets=[viewflowDashboard],
        )
    ]
)

urlpatterns = [
        path("", site.urls),
]
```

It's loading infinitely
![image](https://github.com/viewflow/viewflow/assets/87174125/63445304-c81d-4f25-a210-0febdd36ff83)

**Comment by kmmbvnr** [comment]
Any error in js console?

**Comment by D0wn3r** [comment]
no just a warning because of cookie:

> The cookie "cookietest" does not have an appropriate "SameSite" attribute value. Soon, cookies whose "SameSite" attribute is missing or set to an invalid value will be treated as "Lax". This means that the cookie will no longer be sent in third-party contexts. If your application depends on the availability of this cookie in such contexts, please add the "SameSite=None" attribute. To find out more about the "SameSite" attribute, visit https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by kmmbvnr** [comment]
Is it the latest version from git?

Could you please try to run `renderer = new window.DashRenderer();` in js console? Is it makes any changes?

**Comment by D0wn3r** [comment]
![Screenshot 2024-03-01 092202](https://github.com/viewflow/viewflow/assets/87174125/6d27bc9e-7f2f-4aad-b7b3-01b04842fdff)

Yes it's the latest version from git.
Thank you for your fast support

**Comment by kmmbvnr** [comment]
Thank you for the report.

I've updated the documentation with the missing Input and imports.

Please uninstall and install git version again to ensure that the Dash component is included for auto initialization 

![image](https://github.com/viewflow/viewflow/assets/282529/c36e9276-dcf1-438f-bd95-cbc1199a44b5)

**Comment by D0wn3r** [comment]
Thank you,
It works after doing the command `renderer = new window.DashRenderer();` but not before.
Can you also add
```python
from django.contrib.auth.models import User
from django.utils import timezone
```
To make the demo 100% working

**Comment by D0wn3r** [comment]
nevermind it seems ok. Maybe because of cache
