### ISSUE TITLE
Regarding Viewflow Package

### ISSUE THREAD

**Issue by akshayprakash2712** [viewflow/viewflow#423]
![Screenshot 2024-03-01 143032](https://github.com/viewflow/viewflow/assets/138870643/50315a96-3931-4b9d-b21f-b578db554e8d)
In my Viewflow package It shows an error .I tried to give a view function and shows an error.I will share the Screenshot.In this flow it will go to the storyboard view and render the template.
![Screenshot 2024-03-01 143143](https://github.com/viewflow/viewflow/assets/138870643/657c8bc0-6167-4096-a02a-99178c8ac675)
And the error is the below
![Screenshot 2024-03-01 143230](https://github.com/viewflow/viewflow/assets/138870643/223acc30-00f9-436d-a3de-8d14ec6b6616)
Whats the solution for this?

**Comment by kmmbvnr** [comment]
Seems you mixed old code from viewflow v1 and viewflow v2

there is no viewflow.flow module in v2. Please take a look to the recent documentation for the custom views - https://docs.viewflow.io/workflow/custom_views.html

**Comment by kmmbvnr** [comment]
Seems that code written but ChatGPT - for viewflow v2 you could use custom gpts for that - https://chat.openai.com/g/g-8UHAnOpE3-viewflow-pair-programming
