### ISSUE TITLE
Viewflow  Issue

### ISSUE THREAD

**Issue by akshayprakash2712** [viewflow/viewflow#426]
In my django project i try to implement viewflow workflow.
![Screenshot 2024-03-02 112525](https://github.com/viewflow/viewflow/assets/138870643/15693f67-be67-41f2-82df-c2eaf58d0018)
In this create project is working properly.And in create story the assign button shows an error ,i will share the screenshot.
![Screenshot 2024-03-01 140703](https://github.com/viewflow/viewflow/assets/138870643/b6ac00a0-d316-4fd1-99ce-3ba92f5ea62e)
![Screenshot 2024-03-01 140717](https://github.com/viewflow/viewflow/assets/138870643/a4452745-ad1e-45ff-9e6f-ea9d1a483657)
How to correct the error ?

**Comment by kmmbvnr** [comment]
Thanks for the report. That's fixed in git version. Would be released soon

**Comment by akshayprakash2712** [comment]
When will be the new version tentatively available?
