### ISSUE TITLE
Radio Buttons don't seem to work in the free plan

### ISSUE THREAD

**Issue by simonavril** [viewflow/viewflow#428]
Using a forms.RadioSelect() inside a form does not render the radio buttons.

The Server side renders the vf-field-radio-select tag, but seems like the element is not configured in the frontend?

**Comment by kmmbvnr** [comment]
Thank you for the report.

Yep, indeed it was not included into the OSS build. Should be fixed by 2befa43aa23b44395af8f91f27e86a2bd02a45e7
