### ISSUE TITLE
Issues with WIDGET_RENDERERS in conf.py

### ISSUE THREAD

**Issue by simonavril** [viewflow/viewflow#430]
I tried using WIDGET_RENDERERS as per the comment in conf.py but there's a couple of issues with the code.
1. l41: for key, value in custom.get('WIDGET_RENDERERS', {}) breaks if WIDGET RENDERERS is a dict as it should be. Probably just missing .items()
2. L 43: setting the new value to renderer_class() (callable) is probably also wrong and should just be setting the class as the value of the dict instead of instantiating.

Both issues can be circumverted easily by using tuples in the setting and pointing it to a function that returns a class instead of the class but I feel like it'd be better to fix.

Thanks!

**Comment by kmmbvnr** [comment]
Thanks for the report, indeed, that's part is unfinished

**Comment by kmmbvnr** [comment]
Fixed at 1c0da73841247a38906fcb92dd95345b6428b45b
