### ISSUE TITLE
Using the Package with Django admin panel.

### ISSUE THREAD

**Issue by omargawdat** [viewflow/viewflow#432]
I have already created my admin panel and I want to know if it is possible to use the workflow for booking as just a tab in my existing admin panel is this possible or do I have to use the panel of your package?

<img width="1389" alt="image" src="https://github.com/viewflow/viewflow/assets/53629777/f8de839f-3af6-4bfd-8b49-d406e5837ca4">

**Comment by kmmbvnr** [comment]
As for any django application you can override default viewflow templates - https://docs.viewflow.io/crud/templates.html or write custom views - https://docs.viewflow.io/workflow/custom_views.html calling request.activation.done() in a proper moment

**Comment by kmmbvnr** [comment]
While integrating BPMN workflows into Django admin doesn't seem worth the effort, since django admin is not suppose to be so much customized, the FSM workflow cames with django adimn integration https://docs.viewflow.io/fsm/admin.html demo https://demo.viewflow.io/admin/review/review/
