### ISSUE TITLE
NoReverseMatch at /review/review/379/transition/reject/

### ISSUE THREAD

**Issue by kmmbvnr** [viewflow/viewflow#433]
Internal Server Error: /review/review/379/transition/reject/

NoReverseMatch at /review/review/379/transition/reject/
Reverse for 'list' not found. 'list' is not a valid view function or pattern name.

**Comment by jturmel** [comment]
I just tried to upgrade to Django 5.0 from 4.2 and was seeing some NoReverseMatch for 'delete' as well, I don't have more details but going back to 4.2 resolved it so not upgrading for now.

**Comment by kmmbvnr** [comment]
fixed, was a cookbook demo issue
