### ISSUE TITLE
Default logout does not work

### ISSUE THREAD

**Issue by k-aizawa1991** [viewflow/viewflow#435]
Hi, I use viewflow2.0.0 and thought to found a bug around the logout link.

Logout link in `base_page` does not work and the log say as below.
```bash
Method Not Allowed (GET): /accounts/logout/
Method Not Allowed: /accounts/logout/
[18/Apr/2024 14:07:17] "GET /accounts/logout/ HTTP/1.1" 405 0
```

This looks to be because [GET method for LogoutView was deprecated](https://forum.djangoproject.com/t/deprecation-of-get-method-for-logoutview/25533).(See also [the forum](forum.djangoproject.com/t/showing-method-not-allowed-get-users-logout/26044))

So I think the below code should be modified to POST method.

https://github.com/viewflow/viewflow/blob/0bbb7b21c2bac92c653429e9bd5153506fe4ccf3/viewflow/templates/viewflow/base_page.html#L59-L62

- [FYI] my env
  - Django==5.0.4
  - django-debug-toolbar==4.3.0
  - django-filter==24.2
  - django-viewflow==2.0.0
  - sqlparse==0.4.4

**Comment by kmmbvnr** [comment]
Thank you for the report, fixed in 01e2a0edc6e0d7c543c12bb6915b3837152aff56
