### ISSUE TITLE
Unsuitable static codes in profile page

### ISSUE THREAD

**Issue by k-aizawa1991** [viewflow/viewflow#436]
Hi, I found some some parts for improvement.

Name and email in header of an default profile page are static value such as `John Doe` and `admin@admin.com` (see the below code). It would be better that these values are changed with respect to actual users.

https://github.com/viewflow/viewflow/blob/01e2a0edc6e0d7c543c12bb6915b3837152aff56/viewflow/templates/registration/profile.html#L37-L38

I think these should be some variables like `first_name`, `last_name` or `email`. Or if considering the custom user, These parts should be some block tags as below.
```html
<h1 class="mdc-typography--headline6">{%  block name %}John Doe {% endblock %}</h1>
<h2 class="mdc-typography--subtitle2">{%  block email %}admin@admin.com{% endblock %}</h2>
```

**Comment by kmmbvnr** [comment]
Thank you for the report, Good spot!

I've fixed this in 96a4e86344b84f741ae91c448f14cb324c23c3aa
