### ISSUE TITLE
Reffered task titles should be same

### ISSUE THREAD

**Issue by k-aizawa1991** [viewflow/viewflow#440]
Hi, I found a little bit sense of discomfort for task title in breadclumb list of task pages.

`task_base.html` refferes `task.flow_task.task_title` as task title.

https://github.com/viewflow/viewflow/blob/96a4e86344b84f741ae91c448f14cb324c23c3aa/viewflow/templates/viewflow/workflow/task_base.html#L17

On the other hand, `task.html` refferes `task.title` and `task_detail.html` refferes `task.flow_task` instance. This causes the difference of actual display.

https://github.com/viewflow/viewflow/blob/96a4e86344b84f741ae91c448f14cb324c23c3aa/viewflow/templates/viewflow/workflow/task.html#L22-L24

https://github.com/viewflow/viewflow/blob/96a4e86344b84f741ae91c448f14cb324c23c3aa/viewflow/templates/viewflow/workflow/task_detail.html#L7

I think titles set in `Annotation` class should be displayed there. Therefore, `task.html` and `task_detail.html` should be modified to the `task_base.html`'s implementation.

**Comment by k-aizawa1991** [comment]
I think below code should also be `request.activation.task.flow_task.task_title`

https://github.com/viewflow/viewflow/blob/96a4e86344b84f741ae91c448f14cb324c23c3aa/viewflow/templates/viewflow/workflow/task.html#L14

**Comment by kmmbvnr** [comment]
Thank you for the report, Indeed  this is template inconsistency. I fixed this in https://github.com/viewflow/viewflow/commit/309abdfcccdb6ba136159cf1da8ee9a3c9a2abac
