### ISSUE TITLE
Issue with Initial Filter with multi-select

### ISSUE THREAD

**Issue by SamuelLayNZ** [viewflow/viewflow#441]
Hey I've gotten initial filter working and works pretty well however running into an issue when using multi-choice filters on multiple pages.

Here's two examples:
Type is a charfield on a model with choices set.
On the list view I have
`filterset_initial = {"type": [1, 2, 7, 8, 9]}`
![image](https://github.com/viewflow/viewflow/assets/36492073/45a01b94-da60-4dcc-b45e-f182689da48d)

Second example is a foreign key field on a model
`filterset_initial = {"status": ["1", "2"]}`
![image](https://github.com/viewflow/viewflow/assets/36492073/73d2a3b3-1bb1-48a8-bd87-ee78a8143321)

These filterset_initial settings work fine when you first load the list and work fine on other pages as long as you click filter first.
But if you go straight to the second page with just the initial filters (or even back to the first page with ?page=1) it ignores your initial filters and gives those errors.

May be an issue to be worked out or maybe I'm doing it wrong, let me know!

_Originally posted by @SamuelLayNZ in https://github.com/viewflow/viewflow/issues/381#issuecomment-2084356393_

**Comment by kmmbvnr** [comment]
Thank you for the detailed report. That really helps me to reproduce the issue. Yep it was cased by different behaviour of django QueryDict for list values.

Fixed in 8fb6788b4cff1b97c39e2f1349569acc7c9b8ab5
