### ISSUE TITLE
Display bug in task detail page

### ISSUE THREAD

**Issue by k-aizawa1991** [viewflow/viewflow#442]
Hi, I found a bug in `task_detail` page.

`prev_task.next_task.task_description` seems to be wrong and it always display `default:next_task.flow_task`. It would be `next_task.flow_task.task_description`.

https://github.com/viewflow/viewflow/blob/96a4e86344b84f741ae91c448f14cb324c23c3aa/viewflow/templates/viewflow/workflow/task_detail.html#L34

By the way, I think `default:next_task.flow_task` should be `default:next_task.flow_task.task_title` and this comment is not only for next_task but also for prev_task (This comment is related to #440). 

https://github.com/viewflow/viewflow/blob/96a4e86344b84f741ae91c448f14cb324c23c3aa/viewflow/templates/viewflow/workflow/task_detail.html#L24

**Comment by kmmbvnr** [comment]
Thank you for the report!

Fixed in db8a9eb148fca6cb458cad2d1da4970f8927d210
