### ISSUE TITLE
FSM: how to add dynamic data in on_transition_success?

### ISSUE THREAD

**Issue by ddahan** [viewflow/viewflow#443]
Hi there!
I'm trying to add a FSM log containing the user that made the change (and potentially other dynamic data). I'm not sure how I could do this.

Here is my current code:

```python
class DeclarationFlow:
    state = fsm.State(DeclarationState)

    def __init__(self, declaration):
        self.declaration = declaration

    @state.on_success()
    def _on_transition_success(self, descriptor, source, target):
        with transaction.atomic():
            self.declaration.save()
            DeclarationChangeLog.objects.create(
                declaration=self.declaration,
                source_state=source,
                target_state=target,
                changed_by=??? # this should be passed dynamically
            )

class DeclarationChangeLog(TimeStampable, models.Model):
    declaration = models.ForeignKey(Declaration, related_name="change_logs", on_delete=models.CASCADE)
    source_state = models.CharField(choices=DeclarationState)
    target_state = models.CharField(choices=DeclarationState)
    changed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
```

Thanks for your help.

**Comment by kmmbvnr** [comment]
No magic here, just pass all dependencies to a flow class constructor - https://github.com/viewflow/cookbook/blob/main/fsm101/review/flows.py#L35

**Comment by ddahan** [comment]
Hi! I saw this example, but to me, it's not "dynamic", because passing the user to the `Flow` object would mean it's always the same user, no matter the transition.
In my case, no matter who creates the `Flow` object, it won't be the same user that will be responsible of the transition.

More generally speaking, I need to inject dynamic data in this log object, which is unrelated to the `Flow` object creation/creator.

**Comment by ddahan** [comment]
Well, it's explicit but it lacks reliability because any dev adding a new transition could forget to create this object.
Anyway, I understand it's not possible due to architectural decision, and I'll find another way.
Thanks for tour reply.

**Comment by kmmbvnr** [comment]
I'm not sure how it's possible to forget something to add if there is all other methods around

And what is the other possibility to have this to be implemented? The data should be passed somehow. As class constructor or as transition method parameters
