### ISSUE TITLE
Information about pro plans

### ISSUE THREAD

**Issue by D0wn3r** [viewflow/viewflow#444]
Hello,
I did open a discussion about options it has in pro plans. Because we planning to maybe pay it but we need fews informations to study it
https://github.com/viewflow/viewflow/discussions/438

Best regards,

**Comment by D0wn3r** [comment]
Up please

**Comment by kmmbvnr** [comment]
Please do not open duplicate tickets in the open source repository

For pro version claims please contact directly to mikhail@viewflow.io
