### ISSUE TITLE
No way to add custom data to transition

### ISSUE THREAD

**Issue by Tijs-B** [viewflow/viewflow#445]
I'm trying to migrate from django-fsm to viewflow as django-fsm is deprecated. In django-fsm, there is a way to add [custom properties](https://github.com/viewflow/django-fsm/blob/83a3a080041b7599ec50f43fa8f3dd1e5af97d20/django_fsm/__init__.py#L127) to transition. I used these properties to tag some transitions, and used these properties to filter out some transitions from `get_available_transitions`.

In viewflow, it doesn't seem like there is such a field on `Transition` that can contain arbitrary data. Is there a workaround?

**Comment by kmmbvnr** [comment]
Let me check. Probably i miss that. I would add it soon back

**Comment by Tijs-B** [comment]
Any update @kmmbvnr ? I can also try to implement this myself

**Comment by kmmbvnr** [comment]
Thanks for your help!

I've just added and released 2.1.0

https://github.com/viewflow/viewflow/commit/9b5a5e182ba7174717a9a6bd78f690c12baa56a0#diff-8046891ef177eac8f4de5a551d7cdcd790849d6f8a87816d18a0ddf7669309bb
