### ISSUE TITLE
button form

### ISSUE THREAD

**Issue by joff13** [viewflow/viewflow#453]
hi

I ve created a view- no mater wich djangaö view, i did a test with FormView, TemplateView, function based view... all the same issue.

the form has 2 button one name="save_form" the orthe name="generate_pdf"

to have visual  coherence i used
```

<button class="mdc-button mdc-card__action mdc-card__action--button mdc-button--raised" type="submit" name="generate_pdf">{% trans 'Generate PDF' %}</button>
<button class="mdc-button mdc-card__action mdc-card__action--button mdc-button--raised" type="submit" name="save_form">{{ button|default:"Save" }}</button>
            
```

when i want to serve the pdf, i got 
Unprocessable Entity error 422

the form is valid, the pdf is created... (in a buffer which i eventually saved to file)

if i call the view without the template, it works fine: the pdf reaches the client.

I was wandering that the problem was the js generated by viewflow. so i tryed this

```

<button class=""  type="submit" name="generate_pdf">{% trans 'Generate PDF' %}</button>
<button class="mdc-button mdc-card__action mdc-card__action--button mdc-button--raised" type="submit" name="save_form">{{ button|default:"Save" }}</button>
            
```

no more error, the client get the file, but the form get stuck (cannot click anymore the 2 bottons)

i think the js has some error..

bye

**Comment by kmmbvnr** [comment]
It's likely an issue with [Hotwire/Turbo.](https://turbo.hotwired.dev/) With Hotwire/Turbo, forms are submitted via AJAX, and they expect a proper AJAX response.

When you want to serve a file, you need to add the data-turbo="false" attribute to the button:

```html
<button class="mdc-button mdc-card__action mdc-card__action--button mdc-button--raised" type="submit" name="generate_pdf" data-turbo="false">{% trans 'Generate PDF' %}</button>
<button class="mdc-button mdc-card__action mdc-card__action--button mdc-button--raised" type="submit" name="save_form">{{ button|default:"Save" }}</button>
```

This should prevent Turbo from interfering with the file download and resolve the issue.

**Comment by joff13** [comment]
thanks for the hint that solved the issue related to ajax but introduced anotherone:

with data-turbo="false"

the 

'generate_pdf': ['']

is no more present in 

self.request.POST

**Comment by kmmbvnr** [comment]
I can't reproduce this on the demo

The demo has ability to select cities and export action that download a generated file  by pressing a button with data-turbo="false"

![image](https://github.com/viewflow/viewflow/assets/282529/370688fa-6574-4c1b-aa35-553677dd50ee)

Could you create a reproducible sample of code?

**Comment by kmmbvnr** [comment]
I've added a little clarification  to the docs

https://docs.viewflow.io/forms/quick_start.html

**Comment by joff13** [comment]
Mikhail
I confirm the behaviour, i could reproduce in a fresh project/app
I'll try to send you the project in private

Il giorno ven 28 giu 2024 alle ore 05:52 Mikhail Podgurskiy <
***@***.***> ha scritto:

**Comment by kmmbvnr** [comment]
I was able to reproduce, yep it's a limitation of hotwite/turbo, but overcome it you need only to change `button` tag to `input`

**Comment by joff13** [comment]
yes I was about to send you the test... the workaround is input type

thanks
C

Il giorno ven 28 giu 2024 alle ore 11:19 Mikhail Podgurskiy <
***@***.***> ha scritto:
