### ISSUE TITLE
Hidden input errors are escaped so displaying as raw HTML

### ISSUE THREAD

**Issue by jturmel** [viewflow/viewflow#456]
Scenario:

You have a hidden input field called `invite_code`, we're populating an invite code into this hidden input during sign up, when the form is validated we're defining a clean_invite_code method in the Django form, this comes back with an error if the code is invalid or expired, however since it's hidden, Django places these in non field type errors, or so it seems, but however in the case of Viewflow the errors returned in the template are escaped so instead of the rendered HTML, you get the actual escaped text:

![CleanShot 2024-07-11 at 15 04 12@2x](https://github.com/user-attachments/assets/41741d73-15cd-41a6-a54f-f4e052e0265c)

It's within the vf-form__error div:

![CleanShot 2024-07-11 at 14 28 07@2x](https://github.com/user-attachments/assets/eed1c586-0dee-4d05-b93a-24ce4adcdb54)

**Comment by kmmbvnr** [comment]
Thank you for detailed issue report. Fixed in 2.2.4

d00feaa7eb752b3284d3e9efe14d4b2ea1f95b77
