### ISSUE TITLE
DependentModelSelect in Inlines

### ISSUE THREAD

**Issue by joff13** [viewflow/viewflow#461]
Hi

I'm trying to add DependentModelSelect in a view following documentation and inline comment in widget code.
ther's no way to make it works

Do you have a working example or some hints? maybe it's not compatible with inline forms ?

activating  DependentModelSelect the field in the form disapears

this is the form
 ```
class ProjectInfoForm(ModelForm):
   ...
   CustomerFormSet = inlineformset_factory(
        Project,
        CustomerContactProject,
        fields=['customer','contact'],
        extra=0,
        min_num=1,
        max_num=1,
        validate_min=True,
        validate_max= True,
        can_delete=True,
        widgets = {
             # 'customer': AjaxModelSelect(lookups=['name__istartswith'],), # this works correctly
            'contact': DependentModelSelect(depends_on='customer', queryset=get_customer_queryset)
            }
    )

    project_customers = InlineFormSetField(
        formset_class=CustomerFormSet,
        can_delete=True,
        extra=0,
    )

   ....
```
 this is the  view
```

class ProjectConfigurationView(FormDependentSelectMixin, TaskSuccessUrlMixin, generic.UpdateView):
    template_name = "viewflow/workflow/task.html"
    form_class = ProjectInfoForm
    ....

```

**Comment by kmmbvnr** [comment]
Dependent model select demo available at https://demo.viewflow.io/atlas/sea/11/change/

https://github.com/viewflow/cookbook/blob/main/crud101/atlas/viewset.py#L169

**Comment by cedro0** [comment]
Hello,
when used in InlineFormsetField, the context['widget'] passed in the WidgetRenderer is as follow:

`{'name': 'formset-project_customers_2-__prefix__-contact', 'is_hidden': False, 'required': True, 'value': [''], 'attrs': {'id': 'id_formset-project_customers_2-__prefix__-contact', 'parent': 'customer'}, 'template_name': 'django/forms/widgets/select.html', 'optgroups': [(None, [{'name': 'formset-project_customers_2-__prefix__-contact', 'value': '', 'label': '---------', 'selected': True, 'index': '0', 'attrs': {'selected': True}, 'type': 'select', 'template_name': 'django/forms/widgets/select_option.html', 'wrap_label': True}], 0)]}`

The rendered html code is not correct, the name in vf-field-select and the parent in vf-field-select-depent are not matching:

`<vf-field-select id="id_formset-project_customers_2-0-customer" name="formset-project_customers_2-0-customer" value="" label="Customer" ... </vf-field-select>`

`<vf-field-select-dependent id="id_formset-project_customers_2-0-contact" parent="customer" name="formset-project_customers_2-0-contact" value="" label="Contact" optgroups="[]"></vf-field-select-dependent>`

**Comment by kmmbvnr** [comment]
Yep, indeed, I made a fix and put the demo of using dependent selects into the cookbook

https://github.com/viewflow/cookbook/tree/main/crud101/tasks

Would be released in the next version
