### ISSUE TITLE
Defaults in FSM permission

### ISSUE THREAD

**Issue by orientalperil** [viewflow/viewflow#472]
When a permission is not defined for a transition, it should return True by default.  Instead the code is returning False.  This mistake was added in https://github.com/viewflow/viewflow/commit/88c88f34a8f61e3679a56803d9b586b6e581354e#diff-8046891ef177eac8f4de5a551d7cdcd790849d6f8a87816d18a0ddf7669309bb

**Comment by kmmbvnr** [comment]
It's the design decision to make the defaults are safer by default

**Comment by kmmbvnr** [comment]
To take into account the possibility to bypass permissions checks explicitly, i changed it to return True iff permission=None explicitly specified  the transition decorator

https://github.com/viewflow/viewflow/commit/0cb53aa8e1f2922eab4f57fa3399583298e7390c#diff-8046891ef177eac8f4de5a551d7cdcd790849d6f8a87816d18a0ddf7669309bbR90
