### ISSUE TITLE
Dynamic Splitting?

### ISSUE THREAD

**Issue by sherzberg** [viewflow/viewflow#69]
How would you implement a dynamic splits flow? I'd like to collect responses (yes, no) from 10 different users and Join that. I might also want the number of splits to be based on a previous task results.

Any help would be appreciated!

**Comment by matiasmlforever** [comment]
> Thanks for the perfect example. I was looking for something to illustrate custom flow node creation
> 
> And here it is - https://github.com/kmmbvnr/django-viewflow/tree/master/tests/examples/customnode
> 
> Basically you need to define 2 classes. First `DynamicSplit` to store declarative part of flow definition. In our case it could be `next_node` and `callback` that returns split count.
> 
> Second `DynamicSplitActivation` for runtime task activation logic, where you need to activate next tasks with new token, but all from one token source. Join task will wait for all incoming tasks with the same token source.
> 
> There is some boilerplate code exist in `nodes.py`, but i'm going to remove it in next versions of viewflow.
> 
> Also note that any `GateActivation` and `DynamicSplitActivation` have two methods - execute/activate_next. also from first point of view, it is simple to collapse them in one.
> 
> `viewflow` uses different error handling scenarios in case of exception happens in user level code, such as our callback function.
> 
> If previous task was View task, any exception happens in our callback function will lead to rollback even user view task data (this is useful for the case if we miss something in user input validation, but user could quickly change it).
> 
> But if previous task is a Job, job would be completed successfully, and we will not loose any data, but `DynamicSplit` task would be saved in error state for administrator decision.
> 
> And of course, this error handling scenario could be redefined in custom node, but... it still need to be documented =)
> 
> If something unclear, feel free to ask any question )

Excuse me, but where's the example. :), would you be able to share it with me.
