### ISSUE TITLE
Process "migration"?

### ISSUE THREAD

**Issue by sherzberg** [viewflow/viewflow#74]
One thing I have hated in other BMPN style workflows is that it is very hard to change a process once some have been started. django-viewflow looks simple enough to be able to have some sort of migration process for already started processes. Do you have any tips or future apis for modifying already started processes and tasks?

**Comment by kmmbvnr** [comment]
.Viewflow offers much simple support for migrations tnam most of BPMN tools. In Viewflow task dependencies are not stored in the database, and no actions required on new code version deployment.

The recent release add Obsolete nodes - that handles deleted flow nodes reverences.

The node renaming could be handled with simple datamigration

```
migrations.RunSQL("""
    UPDATE viewflow_task SET flow_task='helloworld/flows.MyFlow.new_name'
    WHERE flow_task='helloworld/flows.MyFlow.old_name'
""")
```

http://docs.viewflow.io/core_concepts.html#flow-migrations
