### ISSUE TITLE
Cannot access documentation

### ISSUE THREAD

**Issue by ahmedxmughal** [viewflow/viewflow#80]
http://docs.viewflow.io/

When I sign in using any service, it gives error.

**Comment by kmmbvnr** [comment]
and what is the error?

**Comment by ahmedxmughal** [comment]
thanks for prompt reply.
http://postimg.org/image/hhsdx7385/

Its kinda same with other services also.

**Comment by ahmedxmughal** [comment]
it worked with my Github account but  was not working with facebook account.
