### ISSUE TITLE
django 1.7+ support?

### ISSUE THREAD

**Issue by Bashar** [viewflow/viewflow#81]
whats the roadmap/plans for supporting atleast django 1.7?

**Comment by kmmbvnr** [comment]
Hi, Bashar

Django 1.7 is supported out of the box since first version of viewflow a
year ago.

Viewflow AGPL have support for django 1.7 only

Viewflow pro - 1.6 and 1.7

Mikhail
19.03.2015 22:47 пользователь "Bashar Al-Abdulhadi" <
notifications@github.com> написал:
