### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#82]
Hi @kmmbvnr would you accept a pull request, adding python2 support? I know there is the "pro" version, but I don't feel comfortable paying 450 bucks for a test. That's quite the entrance barrier.

**Comment by kmmbvnr** [comment]
Nope. It's pretty fine to have a test on python3.3

Python2.7 is mostly production requirement. It's support requires addition efforts from me. 

No free support Python 2.7  will ever be available in any case.

**Comment by codingjoe** [comment]
Based on that, does the pro license allow modifying the code, and redistribution through SAAS (does it have ASP loophole).

**Comment by kmmbvnr** [comment]
Pro version is licensed under commercial friendly licence - https://github.com/viewflow/viewflow/blob/master/COMM-LICENSE.txt

Allows modification and 3d party access.

There is restriction only on software redistribution, don't allows to resell the viewflow/pro itself, not included as part of some product.

**Comment by codingjoe** [comment]
@kmmbvnr thanks, I didn't see that
