### ISSUE TITLE
How to create a sync task without celery?

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#84]
I was wondering how you can just execute a peace of code without using a celery task?

**Comment by kmmbvnr** [comment]
There are flow.Func that should be called explicitly somewhere in the code
and flow.Handler that executes as soon as task activated.

See
https://github.com/viewflow/viewflow/blob/master/tests/integration/tests/test_flow_func.py
for examples
29.04.2015 19:33 пользователь "Johannes Hoppe" <notifications@github.com>
написал:

**Comment by codingjoe** [comment]
@kmmbvnr Thanks, worked. But this could remain as a task for documentation ;)

**Comment by kmmbvnr** [comment]
http://docs.viewflow.io/viewflow_flow.html#viewflow.flow.func.Handler

documentation  extended
