### ISSUE TITLE
Compatibility with Flask and/or RQ

### ISSUE THREAD

**Issue by linkyndy** [viewflow/viewflow#86]
This project sounds very neat and I was wondering how compatible is viewflow with Flask and/or RQ. Or is it designed to work specifically with Django?

**Comment by kmmbvnr** [comment]
Why you need Flask?

I think there is almost impossible to create some reusable person workflow library for the flask and no reason to do that.

First you have to select orm/forms/template/user-and-permission api. If you do that, you'll finished with app that behaves same as django with codebase larger that django with uncommon to most developers structure and requirements.

RQ support is not implemented, but any background task queue could be added just in just a few lines as the celery - https://github.com/viewflow/viewflow/blob/master/viewflow/contrib/celery.py

**Comment by linkyndy** [comment]
I need a very simple workflow in Flask, just some functions defined that need to be run in some order defined by a graph. Those functions will access the database through and ORM. Also, I don't need permissions, forms or templates.

From what you've mentioned, I guess I need to strip viewflow from a lot of its features in order to get a very simple workflow, as I need, right? Do you have in plan to release a very minimal build of viewflow that does just this, define the actual workflow?

**Comment by barseghyanartur** [comment]
@linkyndy:

See the requirements: `django-fsm`. He would have to first do it for `django-fsm` in order to do that. So, I guess the answer would be - no/never. :)

**Comment by kmmbvnr** [comment]
Sounds like non-interactive task. That's boring ;)

Viewflow designed to automate interactive persons tasks (with background task as option). As soon as you have 2 persons that could collaborate concurrently and requires good end user interface, things gets complicated without explicit workflow layer on top of urls/views framework structure.

Viewflow main goal to compete with products like Bizagi or Camunda but became really developers friendly without loosing speed of business process development. 

Automate of background non-interactive jobs execution is really simple. You could take a look to build-in celery workflow - http://celery.readthedocs.org/en/latest/userguide/canvas.html#the-primitives
Or products like - https://github.com/spotify/luigi

**Comment by linkyndy** [comment]
I understand, I was viewing viewflow from a different angle. Thanks for replying and good with the future development of it!
