### ISSUE TITLE
Error in example on the web page

### ISSUE THREAD

**Issue by gergelypolonkai** [viewflow/viewflow#88]
I have just installed viewflow with pip, but typing the examples give me errors:

    from viewflow.views import StartProcessView, ProcessView

    …

        start = flow.Start(StartView, …

This obviously won’t work, as StartView is not imported anywhere (and even if I try it won’t work, as `viewflow.views` doesn’t export such symbol).

**Comment by kmmbvnr** [comment]
Thank you. Fixed both on readme and on web page.
