### ISSUE TITLE
How I can display the graphical BPMN my flow?

### ISSUE THREAD

**Issue by rcorzogutierrez** [viewflow/viewflow#89]

**Comment by kmmbvnr** [comment]
There is the plan to create simple autolayouted png export, but currently it's not implemented.

**Comment by kmmbvnr** [comment]
Charting added to the Viewflow PRO. It's available in the frontend [out of the box](http://demo.viewflow.io/workflow/shipment/shipment/chart.svg/)

Or coulbe be used in a custom view:

```python

from viewflow import chart

def show_svg(request, flow_cls=None):
    grid = chart.calc_layout_data(flow_class)
    svg = chart.grid_to_svg(grid)
    return HttpResponse(svg, content_type="image/svg+xml")
```
