### ISSUE TITLE
Assign callable should be called with the current task rather the the process

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#92]
Currently `Assign` only passes `process` as a argument to the callable, while executing the assign.
I do think it should be the task. It would give you access to the process and allow you do make decisions based on the current, and even previous task.

**Comment by codingjoe** [comment]
e.G. This will not work for parallelisation.
```python
def assign_latest_task_owner(process):
    """Return last task task owner to be assigned for the next task."""
    previous = process.flow_cls.task_cls._default_manager \
            .filter(process=process, finished__isnull=False, owner__isnull=False) \
            .order_by('finished').last()
    return previous.owner
```

**Comment by kmmbvnr** [comment]
Yep, you are right. This is the design mistake and need to be fixed in the next version.

Currently, you can get the expected behavior,  by subclassing from `flow.View` with overrided `calc_owner` method


    class View(flow.View):
        def calc_owner(self, task):
            from django.contrib.auth import get_user_model

            owner = self._owner
            if callable(owner):
                owner = owner(task)  # fix here
            elif isinstance(owner, dict):
                owner = get_user_model() ._default_manager.get(**owner)
            return owner

**Comment by codingjoe** [comment]
Sure, we made it work for us, but good to see that we agree on redesign. Looking forward, thanks.

**Comment by codingjoe** [comment]
yeah 👍

**Comment by aviatorBeijing** [comment]
Have you guys fixed this issue in latest version?
