### ISSUE TITLE
AttributeError: type object 'MyMixin' has no attribute 'prepare'

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#94]
Currently you cant use a view mixin together with a ProcessView.
The error is here:
https://github.com/viewflow/viewflow/blob/master/viewflow/fsm.py#L100

This could be fixed providing `None` as a default.
Tho I don't really get why you need to iterate over the entire superclass tree, but hey there are a lot of parts I haven't wrapped my head around.

**Comment by kmmbvnr** [comment]
Thank you.

The fsm implementation allows to redefine transitions on child subclasses. And lookup for base class transition was done wrong.

Fix released in django-viewflow-pro 0.9.1
