### ISSUE TITLE
Flow visualization support

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#98]
Hi @kmmbvnr,

is there any best practice on how to inspect a flow. I want to build a graphviz extension to improve our documentation just like for fsm.
Let me know if there's any trick, I'll make sure to create a pull-request once I'm done.

Cheers,
joe

**Comment by kmmbvnr** [comment]
I'm not sure that graphviz would be best tool for this. For documentation it's ok, but may be for using the diagrams in end-user portal some js rendering library should be selected. Unfortunately most of them (with price less than 10x viewflow's) have no support for autolayouts.

There is the simple layout algorithm that looks reasonable, but it needs time to be implemented - http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=5210767&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D5210767

The main advantage of graphviz that we need only few lines to get it work. Take a look to this one that I started to develop.

https://github.com/viewflow/viewflow/blob/0.5.0/viewflow/graphviz.py

The initial idea, is to have extension method for each flow node. This should allows end-user  easy to redefine node rendering for custom node subclasses. Stay separate from the core library, and makes me free from decision how node traversal API should looks like.

PS. For the legal issues, I have to add some sort of contribution agreement that will allows me to provide code under dual licencing - https://github.com/bestpractical/rt/blob/stable/README#L306 Hope you will agree on that.

**Comment by codingjoe** [comment]
Hm... ok, I'll look into that. I mostly want it to work as a sphinx extensions. I currently working on a prove of concept. I will probably create a PR for FSM first regarding sphinx.

**Comment by codingjoe** [comment]
BTW, we also thought to use the BPMN library behind bpmn.io to show the process in the frontend.
Essentially because other than a statemachine BPMN is communicated thought the company. Thus making the process diagram available to everyone might make sense.
We're currently very busy getting things to work. But we will have an open source sprint later this year. Let's see what we can come up with.

**Comment by kmmbvnr** [comment]
Added a custom bpmn-specific impl for layout as a part of material-frontend

![workflow material frontend](https://cloud.githubusercontent.com/assets/282529/17845401/5ae2dbce-6863-11e6-8dc4-95485debb1b4.png)

![workflow material frontend2](https://cloud.githubusercontent.com/assets/282529/17845404/5f3f0a9e-6863-11e6-842d-e0398251c1bf.png)

**Comment by codingjoe** [comment]
@kmmbvnr cool, thanks, that looks great. Is there any way to implement this somewhere else? Given of course you have the material package installed.

**Comment by kmmbvnr** [comment]
In the next version of viewflow-pro it would be available as

```
        from viewflow  import graph
        grid = graph.calc_layout_data(self.flow_class)
        svg = graph.grid_to_svg(grid)
        return HttpResponse(svg, content_type="image/svg+xml")
```

**Comment by codingjoe** [comment]
@kmmbvnr very exciting!
We build a very simple version of that for as sphinx extension, you can have your flows documented right away. https://github.com/Thermondo/viewflow-extensions
If you are interested, [check this out](https://github.com/Thermondo/viewflow-extensions/blob/master/viewflow_extensions/sphinx.py). Since you have the SVG, adding a sphinx extension is super straight forward.

**Comment by codingjoe** [comment]
Quick questions, is there like a setting, where one can overwrite the mapping and add customer nodes? Stuff like the conditional events we talked about, would be one use case.

**Comment by kmmbvnr** [comment]
yep, all nodes now have `shape` attr

![viewflow pro func py at master kmmbvnr viewflow pro](https://cloud.githubusercontent.com/assets/282529/17850575/9ff64824-687f-11e6-9a2d-67441324b7f5.png)

**Comment by codingjoe** [comment]
Brilliant, that's great!
So this is based on pure SVG or do you use bpmn.io? I guess the font with all the event types might come in handy.

**Comment by kmmbvnr** [comment]
It's pure svg

**Comment by codingjoe** [comment]
@kmmbvnr I just wanted to integrate it, but I doesn't seem to be released yet, is it?
Do you happen to have an ETA for this feature?

**Comment by kmmbvnr** [comment]
i'm working on release right now. No ETA (

**Comment by codingjoe** [comment]
No problem, just let me know when its ready.

**Comment by acantillo14** [comment]
Hi,
I'm trying to implement the viewflow library, but I want to know what step to carry out to execute the graph of the process

Thanks.

**Comment by sans712** [comment]
If I want graphical view of workflow on clicking on "flow" link as showed in shipment demo ,do I need Viewflow pro for that?
Can't I get workflow graph by using Viewflow only?

**Comment by kmmbvnr** [comment]
@sans712 flow visualization is the part of pro package only

**Comment by sans712** [comment]
Viewflow pro is not an open source right?
