### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#99]
Happens at two points:
https://github.com/viewflow/viewflow/blob/master/viewflow/fields.py#L19
https://github.com/viewflow/viewflow/blob/master/viewflow/fields.py#L62

because of this
https://github.com/viewflow/viewflow/blob/master/viewflow/compat.py#L68

**Comment by kmmbvnr** [comment]
Yep, error message need to be improoved
